### PR TITLE
conn: add skip prepare for control queries

### LINKED ISSUE #1389: Amazon Cassandra : Column family TableIdentifier(ksName=system, cfName=local) is not writable
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
Amazon Managed Cassandra - version 3.11.2

### What version of Gocql are you using?
v0.0.0-20200103014340-68f928edb90a

### What did you do?
Tried to connect to Amazon Managed Cassandra using gocql

```
clusterConfig := gocql.NewCluster("cassandra.us-east-1.amazonaws.com:9142")
clusterConfig.Authenticator = gocql.PasswordAuthenticator{Username: username, Password: password}
clusterConfig.SslOpts = &gocql.SslOptions{
		CaPath: "AmazonRootCA1.pem",
	}

clusterConfig.Keyspace = "test"
session, err := clusterConfig.CreateSession()
```

### What did you expect to see?
Successful gocql Session creation

### What did you see instead?
{"error": "gocql: unable to create session: control: unable to setup connection: Column family TableIdentifier(ksName=system, cfName=local) is not writable"}

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
nodetool: Failed to connect to 'cassandra.us-east-1.amazonaws.com:9142' - ConnectIOException: 'non-JRMP server at remote endpoint'.

- output of `SELECT peer, rpc_address FROM system.peers`

peer | rpc_address
3.83.170.140 | null
3.83.168.142 | null
3.83.169.141 | null
3.83.170.152 | null
3.83.168.154 | null
3.83.169.153 | null
3.83.168.143 | null
3.83.170.151 | null
3.83.171.143 | null

- rebuild your application with the `gocql_debug` tag and post the output

2020-01-13T16:53:55.664-0500	ERROR	filter/filter.go:65	error:	{"error": "gocql: unable to create session: control: unable to setup connection: Column family TableIdentifier(ksName=system, cfName=local) is not writable"}

### PR DESCRIPTION
**Pull request by Zariel**
Control queries only ever do reads on system tables but AWS MCS treats a
prepare as write which it blocks on system tables. We can avoid doing
prepares on selects as long as we get the result metadata.

fixes #1389

### CODE REVIEW

File: session.go [hunk 1]
```diff
@@ -809,6 +809,10 @@ type Query struct {
 
 	// getKeyspace is field so that it can be overriden in tests
 	getKeyspace func() string
+
+	// used by control conn queries to prevent triggering a write to systems
+	// tables in AWS MCS see
```
Comment (martin-sucha) [inline session.go]: a link is missing here?
