### PR TITLE
CASSGO-1 CASSGO-30 Native Protocol 5 Support

### LINKED ISSUE #1750: Cassandra version 5: unsupported protocol error
### What version of Cassandra are you using?
5

### What version of Gocql are you using?
v1.6.0

### What version of Go are you using?
go1.21.6 linux/amd64

### What did you do?
Trying to establish a session with the Cassandra v5 cluster (inside the Docker container) using native protocol v5. I saw that the version 5 protocol was added already, but it seems it is not working properly for some reason. I've debugged the connection process and found that the error happened during the `readHeader()` function execution. 
So, the process of connection according to logs looks like this:
```
stream: 1
framer: &{5 16 <nil> 9 <nil> [] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [] map[]}
p[byte]: [133 0 0 0 0 0 0 0 0]
p[:1]: [133]
version 5

stream: 64
framer: &{5 16 <nil> 9 <nil> [] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [] map[]}
p[byte]: [133 0 0 1 6 0 0 0 102]
p[:1]: [133]
version 5

stream: 128
framer: &{5 16 <nil> 9 <nil> [] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [] map[]}
p[byte]: [114 0 0 64 2 0 0 0 0]
p[:1]: [114]
version 114
_error here_
```

I've compared the connection process using 5 version with 3 and 4 versions of the protocol. It seems pretty similar, except the one thing. When we use the 5 version the first byte always changes from 133 to 114. Now, I am reading the native protocol 5 specification to understand what changes should be made to fix the issue. Will be glad to receive any suggestions regarding it.

Code snippet:
```
	cluster := gocql.NewCluster("172.17.0.2")
	cluster.Consistency = gocql.Quorum
	cluster.ProtoVersion = 5
	cluster.ConnectTimeout = time.Second * 10
	session, err := cluster.CreateSession()
	if err != nil {
		log.Println(err)
		return
	}
	defer session.Close()
```

### What did you expect to see?
Successfully established connection

### What did you see instead?
Error from the gocql:
```
2024/05/13 14:58:01 gocql: unable setup control conn 172.17.0.2:9042: gocql: unsupported protocol response version: 114
2024/05/13 14:58:01 gocql: unable to create session: unable to connect to initial hosts: gocql: unsupported protocol response version: 114
```

Cassandra logs:
```
ERROR [epollEventLoopGroup-5-5] 2024-05-13 11:58:01,959 NoSpamLogger.java:110 - 14ded18b invalid, unrecoverable CRC mismatch detected in frame header. Read 1920, Computed 15624576
WARN  [epollEventLoopGroup-5-5] 2024-05-13 11:58:01,960 NoSpamLogger.java:107 - Protocol exception with client networking: 14ded18b invalid, unrecoverable CRC mismatch detected in frame header. Read 1920, Computed 15624576
```

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

Nodetool status:
```
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load        Tokens  Owns (effective)  Host ID                               Rack 
UN  172.17.0.2  151.72 KiB  16      100.0%            222503c6-0030-43a6-a365-c61aae4b9765  rack1

```

Cqlsh output:

```
root@2e8cb70614b1:/# cqlsh
WARNING: cqlsh was built against 5.0-beta1, but this server is 5.0.  All features may not work!
Connected to Test Cluster at 127.0.0.1:9042
[cqlsh 6.2.0 | Cassandra 5.0-beta1 | CQL spec 3.4.7 | Native protocol v5]
```

### PR DESCRIPTION
**Pull request by worryg0d**
## Overview

C* 4.0 introduced Native Protocol 5, so we should make gocql to support it.
This PR consists of other my PRs, which also provides support for the v5 version of the protocol.

This PR provides support of Native Protocol 5 features as:
* New frames format [CASSANDRA-15299](https://issues.apache.org/jira/browse/CASSANDRA-15299)
* `result_metadata_id` field for **EXECUTE** and **PREPARED** messages [CASSANDRA-10786](https://issues.apache.org/jira/browse/CASSANDRA-10786)
* `now_in_seconds` field for `BATCH` and `QUERY` messages [CASSANDRA-14664](https://issues.apache.org/jira/browse/CASSANDRA-14664)
* `keyspace` field for `BATCH` and `QUERY` messages

closes #1750

### CODE REVIEW

**Comment by worryg0d** [comment]
This PR is merged from #1778, #1773, #1782, and #1781, so we could close them in favor of this one

**Comment by joao-r-reis** [comment]
What about https://github.com/apache/cassandra-gocql-driver/pull/1783

File: frame_test.go [hunk 1]
```diff
@@ -127,3 +131,315 @@ func TestFrameReadTooLong(t *testing.T) {
 		t.Fatalf("expected to get header %v got %v", opReady, head.op)
 	}
 }
+
+func Test_framer_writeExecuteFrame(t *testing.T) {
```
Comment (lukasz-antoniak) [inline frame_test.go:135]: We need an integration test to validate `<result_metadata_id>` logic. Details of why it was included can be found in ticket [CASSANDRA-10786](https://issues.apache.org/jira/browse/CASSANDRA-10786). I am trying to create a test like it.

**Review by lukasz-antoniak — COMMENTED** [review]
Copied unsolved comments fromCopied unresolved comments from previous PRs.

**Comment by lukasz-antoniak** [comment]
> What about #1783

@worryg0d, IMHO changes in #1783 are still needed and improve code maintainability.

**Comment by worryg0d** [comment]
Thanks a lot for reaching out!

This PR is lacking changes from #1783. I will ask @testisnullus if we could merge it into this PR.

**Comment by testisnullus** [comment]
@worryg0d @lukasz-antoniak I think we can keep the current implementation and merge the #1783 PR into this one.

**Comment by worryg0d** [comment]
I merged changes from #1783 into this one.

File: batch_test.go [hunk 2]
```diff
@@ -84,3 +85,84 @@ func TestBatch_WithTimestamp(t *testing.T) {
...
+
+func TestBatch_WithNowInSeconds(t *testing.T) {
+	session := createSession(t)
+	defer session.Close()
+
+	if session.cfg.ProtoVersion < protoVersion5 {
+		t.Skip("Batch now in seconds are only available on protocol >= 5")
+	}
+
+	if err := createTable(session, `CREATE TABLE batch_now_in_seconds (id int primary key, val text)`); err != nil {
```
Comment (joao-r-reis) [inline batch_test.go]: Should we add `IF NOT EXISTS` to make it possible for these tests to run multiple times on the same cluster? Normally it wouldn't matter since a test cluster is created for each run on the github action but locally it could be useful.

File: cassandra_test.go [hunk 3]
```diff
@@ -3288,3 +3289,150 @@ func TestQuery_NamedValues(t *testing.T) {
...
+		t.Fatal(err)
+	}
+
+	var result string
+	err = session.Query("SELECT text_col FROM gocql_test.large_size_query").Scan(&result)
+	if err != nil {
+		t.Fatal(err)
+	}
+
+	require.Equal(t, str, result)
```
Comment (joao-r-reis) [inline cassandra_test.go:3566]: What is being tested on these last two tests?

File: compressor.go [hunk 4]
```diff
@@ -32,6 +32,7 @@ type Compressor interface {
 	Name() string
 	Encode(data []byte) ([]byte, error)
 	Decode(data []byte) ([]byte, error)
+	DecodeSized(data []byte, size uint32) ([]byte, error)
```
Comment (joao-r-reis) [inline compressor.go]: Hmm this would technically be a breaking change but I don't think there's much we can do. Good thing this is going into a 2.0.0 release so we don't have to worry about this being a breaking change 👍 .

File: conn.go [hunk 5]
```diff
@@ -474,8 +483,12 @@ func (s *startupCoordinator) startup(ctx context.Context, supported map[string][
 	case error:
 		return v
 	case *readyFrame:
+		// Connection is successfully set up and ready to use Native Protocol v5
+		s.conn.startupCompleted = true
```
Comment (joao-r-reis) [inline conn.go]: Don't we need some kind of sychronization around this field? Or atomic access?

File: session.go [hunk 6]
```diff
@@ -1423,6 +1427,25 @@ func (q *Query) releaseAfterExecution() {
...
+	return q
+}
+
+// WithNowInSeconds will enable the with now_in_seconds flag on the query.
+// Also, it allows to define now_in_seconds value.
+//
+// Only available on protocol >= 5.
+func (q *Query) WithNowInSeconds(now int) *Query {
+	q.useNowInSeconds = true
+	q.nowInSecondsValue = now
```
Comment (joao-r-reis) [inline session.go]: I wonder if we should just use `*int` on the internal field so we can check if it's `nil` and therefore remove the need of having a separate `useNowInSeconds` flag

File: frame.go [hunk 7]
```diff
@@ -1503,18 +1523,21 @@ func (f *framer) writeQueryParams(opts *queryParams) {
...
 	}
 
-	if opts.keyspace != "" {
-		if f.proto > protoVersion4 {
+	// protoV5 specific things
+	if f.proto > protoVersion4 {
+		if opts.keyspace != "" {
 			flags |= flagWithKeyspace
-		} else {
-			panic(fmt.Errorf("the keyspace can only be set with protocol 5 or higher"))
```
Comment (joao-r-reis) [inline frame.go:1499]: We should keep this panic (or return an error) if the user tries to set the keyspace but protocol version is not > 4

File: frame.go [hunk 8]
```diff
@@ -1717,25 +1759,46 @@ func (f *framer) writeBatchFrame(streamID int, w *writeBatchFrame, customPayload
 		if w.defaultTimestamp {
 			flags |= flagDefaultTimestamp
 		}
+	}
 
-		if f.proto > protoVersion4 {
-			f.writeUint(uint32(flags))
+	if f.proto > protoVersion4 {
+		if w.keyspace != "" {
+			flags |= flagWithKeyspace
```
Comment (joao-r-reis) [inline frame.go]: same as above, panic or return error if user tries to set keyspace but protocol is not > 4

File: conn.go [hunk 9]
```diff
@@ -1430,6 +1525,24 @@ func (c *Conn) executeQuery(ctx context.Context, qry *Query) *Iter {
...
+				return c.executeQuery(ctx, qry)
+			}
+
+			// Updating the result metadata id in prepared stmt
+			//
+			// If a RESULT/Rows message reports
+			//      changed resultset metadata with the Metadata_changed flag, the reported new
+			//      resultset metadata must be used in subsequent executions
+			inflight.preparedStatment.resultMetadataID = x.meta.newMetadataID
+			inflight.preparedStatment.response = x.meta
```
Comment (joao-r-reis) [inline conn.go]: Hmm I think there might be a synchronization issue here as well, other goroutines can be accessing this preparedstatement object at the same time. Ideally the prepared statement object should be immutable so we could just replace the entire object in the cache instead of trying to modify it. This would get rid of the synchronization issue.

**Review by joao-r-reis — COMMENTED** [review]
First pass review. I'll need some extra time to properly review the envelope/message format changes.

**Comment by worryg0d** [comment]
Hey, @joao-r-reis. Thanks a lot for your feedback! I'm pleased this PR is moving. I will take a look at your comments and suggestions tomorrow. I hope everything will be fine here.

File: batch_test.go (hunk 2 above)
Comment (worryg0d) [reply batch_test.go]: As far as I know `createSession` internally calls `createKeyspace` which deletes old **gocql_test** keyspace and creates a new one. So, it doesn't matter even if we run these tests locally, or each test individually. However, it is not a big change so I'll add it to tests.

File: cassandra_test.go (hunk 3 above)
Comment (worryg0d) [reply cassandra_test.go:3566]: `TestLargeSizeQuery` runs a query bigger than the max allowed size of the payload of an envelope, so it should be sent as 2 different frames where each contains a self-contained bit set to zero.

`TestQueryCompressionNotWorthIt` runs a query that is not likely to be compressed efficiently (uncompressed payload size > compressed payload size). So, it should send a **Compressed Frame** where:
- **Compressed length** is set to the length of the uncompressed payload;
- **Uncompressed length** is set to zero;
- **Payload** is the uncompressed payload.

I agree that the point of those tests is not clear, but from my point of view, we should have some integration tests for this as well.

File: conn.go (hunk 5 above)
Comment (worryg0d) [reply conn.go]: As I see `Conn.startupCompleted` is being read by:

- [Conn.serve](https://github.com/apache/cassandra-gocql-driver/blob/953e0df999cabb3f5eef714df9921c00e9f632c2/conn.go#L587) which is run by [Conn.init](https://github.com/apache/cassandra-gocql-driver/blob/953e0df999cabb3f5eef714df9921c00e9f632c2/conn.go#L306) after `startup.setupConn` is finished. [startupCoordinator.setupConn](https://github.com/apache/cassandra-gocql-driver/blob/953e0df999cabb3f5eef714df9921c00e9f632c2/conn.go#L372) sends **STARTUP** as not framed envolope, receives **READY** or **AUTHENTICATE** and sets `Conn.startupCompleted` to true.
`Conn.serve` is running in a separate go routine
- [Conn.exec](https://github.com/apache/cassandra-gocql-driver/blob/953e0df999cabb3f5eef714df9921c00e9f632c2/conn.go#L1029) which sends queries to C* and returns `framer` which contains C* response.
`Conn.exec` is also running in different go routines.

As I see there are no sync issues because `Conn.serve` is run after the `startupCoordinator.startup` is completed, so it already reads messages from C* by using proto v5. Even if during startup it receives **AUTHENTICATE** response from C*, it will respond with **AUTH_RESPONSE** using proto v5.

File: session.go (hunk 6 above)
Comment (worryg0d) [reply session.go]: It sounds like a cool idea! I'm going to change it as well

File: frame.go (hunk 7 above)
Comment (worryg0d) [reply frame.go:1499]: Now I'm looking at it and releasing that that was a bit greedy decision to get rid of those panics. I'll change this one too

File: conn.go (hunk 9 above)
Comment (worryg0d) [reply conn.go]: Could you please add some details here? On replacing the entire object you mean just replacing `inflight.preperadStatment`? Or replacing the whole `inflight` inside the cache? For the second variant, I could implement it the same way as handling of **UNPREPARED** response message is implemented.

File: batch_test.go (hunk 2 above)
Comment (worryg0d) [reply batch_test.go]: I added this to the PR.

File: session.go (hunk 6 above)
Comment (worryg0d) [reply session.go]: It's done.

File: frame.go (hunk 7 above)
Comment (worryg0d) [reply frame.go:1499]: And this one got changed.

File: frame.go (hunk 8 above)
Comment (worryg0d) [reply frame.go]: The same as above.

**Comment by worryg0d** [comment]
Hello, @joao-r-reis. I added some changes following your comments and suggestions. Could you please take a look at this one again? Also, I have a question regarding to cache of prepared statements. Could you please look at this one too?

Thanks a lot.

File: cassandra_test.go (hunk 3 above)
Comment (joao-r-reis) [reply cassandra_test.go:3566]: Yeah they make sense with your explanation, maybe adding that explanation as a comment would make sense here

File: conn.go (hunk 5 above)
Comment (joao-r-reis) [reply conn.go]: Yes but if `startupCompleted` is not `atomic` then there is no guarantee that the goroutine that reads this field will get the most recent value since the goroutine that writes it is a different one no?

File: conn.go (hunk 9 above)
Comment (joao-r-reis) [reply conn.go]: Doing it the same way as handling of `UNPREPARED` is not really ideal, it is just evicting the prepared statement from the cache and forcing the driver to re-prepare.

Replacing `inflight.preparedStatement` won't fix anything unless this field is made `atomic`, I was thinking of replacing the whole `inflight` object in the cache so we don't have to worry about synchronization or having to make things `atomic` (since the cache itself already does this). I think this can be done by creating a new `inflight` object (with a new copy of the `preparedStatement` object) and just calling `*preparedLRU.add` since it looks like it has "upsert" semantics.

File: batch_test.go (hunk 2 above)
Comment (joao-r-reis) [reply batch_test.go]: Oh I didn't realize the keyspace is being re-created

File: conn.go (hunk 5 above)
Comment (worryg0d) [reply conn.go]: `startupCoordinator.setupConn` is complex, so I'll add its code to this message for clarification
```go
func (s *startupCoordinator) setupConn(ctx context.Context) error {
	var cancel context.CancelFunc
	if s.conn.timeout > 0 {
		ctx, cancel = context.WithTimeout(ctx, s.conn.timeout)
	} else {
		ctx, cancel = context.WithCancel(ctx)
	}
	defer cancel()

	startupErr := make(chan error)
	go func() { // the reading goroutine
		for range s.frameTicker {
			err := s.conn.recv(ctx)
			if err != nil {
				select {
				case startupErr <- err:
				case <-ctx.Done():
				}

				return
			}
		}
	}()

	go func() { // the writing one
		defer close(s.frameTicker)
		err := s.options(ctx)
		select {
		case startupErr <- err:
		case <-ctx.Done():
		}
	}()

	select {
	case err := <-startupErr:
		if err != nil {
			return err
		}
	case <-ctx.Done():
		return errors.New("gocql: no response to connection startup within timeout")
	}

	return nil
}
```

It runs two goroutines: the first listening for response from C* and the second for processing startup.
The first gorounite starts listening data from C* when the `startupCoordinator.frameTicker` chan is not empty.
The second goroutine sends queries to C* via [startupCoordinator.write](https://github.com/apache/cassandra-gocql-driver/blob/953e0df999cabb3f5eef714df9921c00e9f632c2/conn.go#L417) which also writes to `startupCoordinator.frameTicker` chan. So, the reading from C* only starts when the **writing gouroutine** sends a query to the C*, the both goroutines are synchronized by `startupCoordinator.frameTicker`. Once the startup is completed, those goroutines are finished.

When `startupCoordinator.setupConn` is finished, `Conn.init` runs two new goroutines: one for connection serving, and another one for a heartbeat, so they both already have an updated state of `startupCompleted`.

File: cassandra_test.go (hunk 3 above)
Comment (worryg0d) [reply cassandra_test.go:3566]: Then I'll add it

File: conn.go (hunk 5 above)
Comment (joao-r-reis) [reply conn.go]: I think there's a way to avoid using `atomic`... You'd have to remove the field from the `Conn` object completely and pass it to `exec()` and `recv()` as an argument which doesn't seem too complicated to do. Maybe `exec` can become a wrapper around an `internalExec` so we don't have to set `startupCompleted` on all places that call `exec` where `startupCompleted` is always `true` (like `executeQuery`, `executeBatch`, `heartBeat`, etc.)

File: conn.go (hunk 9 above)
Comment (worryg0d) [reply conn.go]: Oh, now I see. Indeed, we could just create a copy of the `inflight.preparedStatement`, update its metadata and **result_metadata_id**, and upsert the updated one to the cache. 
I'll update this one as well.

Comment (joao-r-reis) [reply conn.go]: I'd say create a copy of `inflight.preparedStatement` but also of the `inflight` object itself to ensure no other goroutine is reading the `inflight` object that we're modifying with the new `preparedStatement`

File: conn.go (hunk 5 above)
Comment (worryg0d) [reply conn.go]: Removing it from the **Conn** object and passing its value explicitly to `recv()` may cause some problems at the startup phase because it runs its own reading goroutine which we should notify when it should use native proto v5 when it comes to parsing **AUTHENTICATE** response message:
```
	go func() { // the reading goroutine
		for range s.frameTicker {
			err := s.conn.recv(ctx)
			if err != nil {
				...
			}
		}
	}()
```

Comment (joao-r-reis) [reply conn.go]: Ok I understand, the `startupErr` and `frameTicker` channels ensure that everything is properly synchronized before we return the `conn` object so there's no race.

I still think this is very obscure as it stands, having shared state like this is not great... Is there any other field that is being "implictly" synchronized like this? `frameTicker` wasn't really meant to synchronize shared state if I understand correctly, it was probably just meant to notify `recv()` that a response is expected.

I can easily see a bug being introduced in the future because the visibility of `startupCompleted` is being ensured by channel operations that have a different main purpose and I doubt a dev looking at this code for the first time will recognize this.

Comment (worryg0d) [reply conn.go]: > Is there any other field that is being "implictly" synchronized like this?

Specifically, I did this way only for `startupCompleted` and any other occurrences I didn't meet

> I doubt a dev looking at this code for the first time will recognize this.

Oh, I didn't look from this side... Then we could use atomics here, but the whole implementation won't change much. It still will update the state of `startupCompleted` inside during `startup()` for the **AUTHENTICATE** message if there it is. Or maybe implicitly call `recv()` the second time... Ok, I'll look at what I can do here.

Comment (joao-r-reis) [reply conn.go]: How do you feel about [this](https://github.com/joao-r-reis/gocql/commit/6b6ecf5b857da57d1068a3af547b35430ec7b496), I must admit I didn't test this at all but if this works then we don't have a shared state without explicit synchronization AND we don't have to perform atomic operations after the handshake is done so no performance penalty.

Comment (worryg0d) [reply conn.go]: It looks good to me. It provides atomic access and notifies if the startup is completed for auth message handling as well. I could take it and test

**Comment by ribaraka** [comment]
https://issues.apache.org/jira/browse/CASSANDRA-20004

File: cassandra_test.go (hunk 3 above)
Comment (worryg0d) [reply cassandra_test.go:3566]: I added descriptions for those tests

File: conn.go (hunk 5 above)
Comment (worryg0d) [reply conn.go]: I tested this approach and everything is working fine. It passed integration and unit tests successfully.

**Comment by joao-r-reis** [comment]
I'm reviewing the protocol/envelope changes for the new protocol v5 frame format and one thing I'm noticing is that the name `frame` can either reference the "old frame" (called envelope in v5) or the "new frame" and you can't really tell easily which one it is when reading a particular function that references that name (one has to read the "surrounding" code to understand where it is being called and if it refers to the protocol v5 format or not).

In the java driver this was avoided by calling the new v5 frame a "segment" while "frame" essentially always refers to the envelope (so "frame" remains the same as a concept). It's not ideal to use a word that is not even referenced in the protocol spec but I think having this clear distinction between the two would be very helpful to make the code easier to read (also prevents bugs by someone conflating the two while modifying the code).

File: conn.go (hunk 9 above)
Comment (worryg0d) [reply conn.go]: And this one is added too

**Comment by worryg0d** [comment]
> I'm reviewing the protocol/envelope changes for the new protocol v5 frame format and one thing I'm noticing is that the name `frame` can either reference the "old frame" (called envelope in v5) or the "new frame" and you can't really tell easily which one it is when reading a particular function that references that name (one has to read the "surrounding" code to understand where it is being called and if it refers to the protocol v5 format or not).
> 
> In the java driver this was avoided by calling the new v5 frame a "segment" while "frame" essentially always refers to the envelope (so "frame" remains the same as a concept). It's not ideal to use a word that is not even referenced in the protocol spec but I think having this clear distinction between the two would be very helpful to make the code easier to read (also prevents bugs by someone conflating the two while modifying the code).

I agree because I had the same problems distinguishing frames and envelopes. I wanted to call it another way, but according to proto spec, it should be called as **frames** so I decided to leave this part until it got reviewed. Then we could call it **Segment** instead of frame. Also, it makes it easy for other contributors (e.a. from java-driver) to distinguish them.

File: conn.go [hunk 10]
```diff
@@ -1430,6 +1529,34 @@ func (c *Conn) executeQuery(ctx context.Context, qry *Query) *Iter {
...
+			//
+			// If a RESULT/Rows message reports
+			//      changed resultset metadata with the Metadata_changed flag, the reported new
+			//      resultset metadata must be used in subsequent executions
+
+			stmtCacheKey := c.session.stmtsLRU.keyFor(c.host.HostID(), c.currentKeyspace, qry.stmt)
+			oldInflight, ok := c.session.stmtsLRU.get(stmtCacheKey)
+			if !ok {
+				// We didn't find the stmt in the cache, so we just re-prepare it
+				return c.executeQuery(ctx, qry)
```
Comment (joao-r-reis) [inline conn.go]: if we can't find the stmt in the cache here we can probably just return the rows normally and skip trying the update of the result metadata id. If the user submits the query again then the driver will re-prepare.

File: conn.go [hunk 11]
```diff
@@ -1430,6 +1529,34 @@ func (c *Conn) executeQuery(ctx context.Context, qry *Query) *Iter {
...
+				preparedStatment: &preparedStatment{
+					id:               oldInflight.preparedStatment.id,
+					resultMetadataID: x.meta.newMetadataID,
+					request:          oldInflight.preparedStatment.request,
+					response:         x.meta,
+				},
+			}
+
+			c.session.stmtsLRU.add(stmtCacheKey, newInflight)
+			return c.executeQuery(ctx, qry)
```
Comment (joao-r-reis) [inline conn.go]: I don't think this is right, if I understand correctly all we want to do is update the result metadata ID and use the new result metadata that is on this response instead of the cached one. I don't think it should trigger a new execution of the query. @lukasz-antoniak does my description seem accurate according to the investigation you did while trying to write a test for this?

File: conn.go [hunk 12]
```diff
@@ -378,10 +379,19 @@ func (s *startupCoordinator) setupConn(ctx context.Context) error {
 	}
 	defer cancel()
 
+	// Only for proto v5+.
+	// Indicates if STARTUP has been completed.
+	// github.com/apache/cassandra/blob/trunk/doc/native_protocol_v5.spec
+	// 2.3.1 Initial Handshake
+	// 	In order to support both v5 and earlier formats, the v5 framing format is not
+	//  applied to message exchanges before an initial handshake is completed.
+	startupCompleted := &atomic.Bool{}
```
Comment (joao-r-reis) [inline conn.go:349]: This will cause the minimum Go version to be 1.19 (instead of the current 1.17 according to my experiments). I raised this on the ASF slack channel to see if people think it's ok otherwise we might have to use `atomic.Value` instead...

File: frame.go [hunk 13]
```diff
@@ -1556,8 +1578,18 @@ func (f *framer) writeQueryParams(opts *queryParams) {
...
+			panic(fmt.Errorf("the keyspace can only be set with protocol 5 or higher"))
+		}
 		f.writeString(opts.keyspace)
 	}
+
+	if opts.nowInSeconds != nil {
+		if f.proto < protoVersion5 {
+			panic(fmt.Errorf("now_in_seconds can only be set with protocol 5 or higher"))
+		}
+		f.writeInt(int32(*opts.nowInSeconds))
```
Comment (joao-r-reis) [inline frame.go:1581]: NIT: it would make a bit more sense to do these checks and panics earlier in the function when the header flags are being added (similar to how it was before).

Same for the batch write function

**Review by joao-r-reis — COMMENTED** [review]
Looking good, added a few comments. Still working on the v5 frame format review (I'm reading up on the format spec and also reading some java driver code for comparison)

File: conn.go (hunk 10 above)
Comment (worryg0d) [reply conn.go]: Tbh this part is tricky for me because I can't properly test it with C*. I think you have a point. If **RESULT/ROWS** contains both `<new_metadata_id>` and retrieved rows then it makes sense to return the data instead of re-executing the query, even if the statement is not presented in the cache.

File: conn.go (hunk 12 above)
Comment (worryg0d) [reply conn.go:349]: Oops, I missed it. It's kinda a shame that we can't use more distinguishing atomic types instead of generic `Value`... However, the code base already has some similar things, so changing it is not a very big problem.

File: conn.go (hunk 10 above)
Comment (joao-r-reis) [reply conn.go]: Yeah @lukasz-antoniak was having issues trying to test this too, I'll see if I can reproduce this after I'm done reviewing the v5 frame format

File: conn.go (hunk 12 above)
Comment (joao-r-reis) [reply conn.go:349]: Yeah I'd rather use `atomic.Bool` and `1.19` is 3 versions behind what we currently officially support anyway so personally I don't think it is a big deal to bump the version on `go.mod` to `1.19` but let's see if others chime in

File: frame.go (hunk 13 above)
Comment (worryg0d) [reply frame.go:1581]: Very good catch! Somehow it didn't occur to me... I added a little fix for this one.

We probably should do the same for other fields.

File: conn.go (hunk 10 above)
Comment (worryg0d) [reply conn.go]: Thanks a lot! It will help much

File: conn.go (hunk 12 above)
Comment (worryg0d) [reply conn.go:349]: Then I'll leave it by the time when we receive some feedback on it

File: conn.go [hunk 14]
```diff
@@ -1756,6 +1888,41 @@ func (c *Conn) awaitSchemaAgreement(ctx context.Context) (err error) {
...
+		} else {
+			segment, _, err = readUncompressedFrame(c.r)
+		}
+		if err != nil {
+			return fmt.Errorf("gocql: failed to read non self-contained frame: %w", err)
+		}
+
+		// Write the segment to the destination writer
+		n, _ := dst.Write(segment)
+		read += n
```
Comment (joao-r-reis) [inline conn.go]: We're assuming here that this segment contains a single partial envelope since we're copying the entire payload into the buffer without any checks. I think this is a correct assumption but I still think it wouldn't hurt to check that we're not adding more bytes to the buffer than what we expect. If this check fails we can return a custom protocol error so `go.serve` logs and closes the connection.

File: conn.go [hunk 15]
```diff
@@ -1756,6 +1888,41 @@ func (c *Conn) awaitSchemaAgreement(ctx context.Context) (err error) {
...
+func (c *Conn) recvLastsFrames(dst *bytes.Buffer, bytesToRead int) error {
+	var read int
+	var segment []byte
+	var err error
+	for read != bytesToRead {
+		// Read frame based on compression
+		if c.compressor != nil {
+			segment, _, err = readCompressedFrame(c.r, c.compressor)
+		} else {
+			segment, _, err = readUncompressedFrame(c.r)
```
Comment (joao-r-reis) [inline conn.go]: We could check the self contained flag to make sure it is false and if it's not then return a custom "protocol error" so `go.serve` logs it and closes the connection.

File: conn.go [hunk 16]
```diff
@@ -1756,6 +1888,41 @@ func (c *Conn) awaitSchemaAgreement(ctx context.Context) (err error) {
 	return fmt.Errorf("gocql: cluster schema versions not consistent: %+v", schemas)
 }
 
+// recvLastsFrames reads proto v5 frames from Conn.r and writes decoded payload to dst.
+// It reads data until the bytesToRead is reached.
+// If Conn.compressor is not nil, it processes Compressed Format frames.
+func (c *Conn) recvLastsFrames(dst *bytes.Buffer, bytesToRead int) error {
```
Comment (joao-r-reis) [inline conn.go]: NIT: rename to `recvPartialFrames`
Or if you prefer `recvLastFrames` then just fix the typo

File: conn.go [hunk 17]
```diff
@@ -1756,6 +1888,41 @@ func (c *Conn) awaitSchemaAgreement(ctx context.Context) (err error) {
...
+	var read int
+	var segment []byte
+	var err error
+	for read != bytesToRead {
+		// Read frame based on compression
+		if c.compressor != nil {
+			segment, _, err = readCompressedFrame(c.r, c.compressor)
```
Comment (joao-r-reis) [inline conn.go]: NIT: rename `segment` to `payload` or `segmentPayload` or even `frame` to clarify that this byte slice only contains the payload (frame in old notation / envelope in new notation) and not necessarily the entire segment

File: conn.go [hunk 18]
```diff
@@ -1756,6 +1888,41 @@ func (c *Conn) awaitSchemaAgreement(ctx context.Context) (err error) {
...
+
+		// Write the segment to the destination writer
+		n, _ := dst.Write(segment)
+		read += n
+	}
+
+	return nil
+}
+
+func (c *Conn) processAllEnvelopesInFrame(ctx context.Context, r *bytes.Reader) error {
```
Comment (joao-r-reis) [inline conn.go]: rename to `processAllFramesInSegment`

File: conn.go (hunk 16 above)
Comment (joao-r-reis) [reply conn.go]: NIT: also can we move this function so it is located right after `recvProtoV5Frame`? It would help with code navigation

File: conn.go [hunk 19]
```diff
@@ -777,6 +801,47 @@ func (c *Conn) handleTimeout() {
 	}
 }
 
+func (c *Conn) recvProtoV5Frame(ctx context.Context) error {
```
Comment (joao-r-reis) [inline conn.go]: rename `recvProtoV5Frame` to `recvSegment` (I'd say not to include the protocol version in the name since there will eventually be a protocol v6 that will very likely follow this format)

File: conn.go [hunk 20]
```diff
@@ -777,6 +801,47 @@ func (c *Conn) handleTimeout() {
...
+	var (
+		payload         []byte
+		isSelfContained bool
+		err             error
+	)
+
+	// Read frame based on compression
+	if c.compressor != nil {
+		payload, isSelfContained, err = readCompressedFrame(c.r, c.compressor)
```
Comment (joao-r-reis) [inline conn.go]: rename `payload` to `frame`

File: frame.go [hunk 21]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+	computedPayloadCRC32 := ChecksumIEEE(payload)
+	readPayloadCRC32 := binary.LittleEndian.Uint32(header[:4])
+	if computedPayloadCRC32 != readPayloadCRC32 {
+		return nil, false, fmt.Errorf("gocql: payload crc32 mismatch, computed: %d, got: %d", computedPayloadCRC32, readPayloadCRC32)
+	}
+
+	return payload, isSelfContained, nil
+}
+
+func newUncompressedFrame(payload []byte, isSelfContained bool) ([]byte, error) {
```
Comment (joao-r-reis) [inline frame.go]: rename to `newUncompressedSegment`

File: frame.go [hunk 22]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+	copy(frame[headerSize:], payload) // Copy the payload to the frame
+
+	// Calculate CRC32 for the payload
+	payloadCRC32 := ChecksumIEEE(payload)
+	binary.LittleEndian.PutUint32(frame[headerSize+payloadLen:], payloadCRC32)
+
+	return frame, nil
+}
+
+func newCompressedFrame(uncompressedPayload []byte, isSelfContained bool, compressor Compressor) ([]byte, error) {
```
Comment (joao-r-reis) [inline frame.go]: rename to `newCompressedSegment`

File: frame.go [hunk 23]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+
+	// Compute and write the CRC32 checksum of the payload
+	payloadChecksum := ChecksumIEEE(compressedPayload)
+	binary.LittleEndian.PutUint32(headerBuf[:], payloadChecksum)
+	buf.Write(headerBuf[:4])
+
+	return buf.Bytes(), nil
+}
+
+func readCompressedFrame(r io.Reader, compressor Compressor) ([]byte, bool, error) {
```
Comment (joao-r-reis) [inline frame.go]: rename to `readCompressedSegment`

File: conn.go [hunk 24]
```diff
@@ -777,6 +801,47 @@ func (c *Conn) handleTimeout() {
...
+	if isSelfContained {
+		return c.processAllEnvelopesInFrame(ctx, bytes.NewReader(payload))
+	}
+
+	head, err := readHeader(bytes.NewReader(payload), c.headerBuf[:])
+	if err != nil {
+		return err
+	}
+
+	const envelopeHeaderLength = 9
```
Comment (joao-r-reis) [inline conn.go]: rename to `frameHeaderLength`

File: conn.go [hunk 25]
```diff
@@ -1756,6 +1888,41 @@ func (c *Conn) awaitSchemaAgreement(ctx context.Context) (err error) {
 	return fmt.Errorf("gocql: cluster schema versions not consistent: %+v", schemas)
 }
 
+// recvLastsFrames reads proto v5 frames from Conn.r and writes decoded payload to dst.
```
Comment (joao-r-reis) [inline conn.go]: NIT: `reads proto v5 segments from Conn.r and writes decoded partial frames to dst.`

File: crc.go [hunk 26]
```diff
@@ -0,0 +1,58 @@
...
+	"hash/crc32"
+)
+
+var (
+	// Initial CRC32 bytes: 0xFA, 0x2D, 0x55, 0xCA
+	initialCRC32Bytes = []byte{0xfa, 0x2d, 0x55, 0xca}
+)
+
+// ChecksumIEEE calculates the CRC32 checksum of the given byte slice.
+func ChecksumIEEE(b []byte) uint32 {
```
Comment (joao-r-reis) [inline crc.go]: NIT: I think it would be better for readability to reference `Crc32` and `Crc24` in the name of these two functions instead of `IEEE` and `Koopman`

File: conn.go [hunk 27]
```diff
@@ -694,7 +718,7 @@ func (c *Conn) recv(ctx context.Context) error {
 	} else if head.stream == -1 {
 		// TODO: handle cassandra event frames, we shouldnt get any currently
 		framer := newFramer(c.compressor, c.version)
-		if err := framer.readFrame(c, &head); err != nil {
+		if err := framer.readFrame(r, &head); err != nil {
 			return err
 		}
 		go c.session.handleEvent(framer)
```
Comment (joao-r-reis) [inline conn.go:681]: Line 730:
```
if err := framer.readFrame(c, &head); err != nil {
			return err
}
```
This should be changed to `r` as well right? 

I don't like that `Conn` implements `io.Reader` and also has a `*bufio.Reader` field, it makes it very easy to use one when we actually wanted the other... 

I think this is even the case on `readUncompressedFrame` and `readCompressedFrame`... It's using `c.r` directly but it should be using `c` so the additional logic from `Conn.Read()` is used right?

I think we should create a type (maybe `connReader`?) that wraps the `*bufio.Reader` object and then move the implementation of `Conn.Read()` to that new type so we ensure that we only have one object that implements `io.Reader`. This way `c.r` becomes an object of `*connReader` instead of `*bufio.Reader`, `Conn` no longer implements `io.Reader` and everytime we want to actually read from the socket we have to use the `c.r` field instead of `c` directly.

File: frame.go [hunk 28]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+	header := [headerSize + 1]byte{}
+
+	// Read the frame header
+	if _, err := io.ReadFull(r, header[:headerSize]); err != nil {
+		return nil, false, fmt.Errorf("gocql: failed to read uncompressed frame, err: %w", err)
+	}
+
+	// Compute and verify the header CRC24
+	computedHeaderCRC24 := KoopmanChecksum(header[:3])
+	readHeaderCRC24 := binary.LittleEndian.Uint32(header[3:]) & 0xFFFFFF
```
Comment (joao-r-reis) [inline frame.go]: Replace with `readHeaderCRC24 := uint32(header[3]) | uint32(header[4])<<8 | uint32(header[5])<<16`
so that we can declare the header as a `6` byte array instead of `7`

File: frame.go [hunk 29]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+	if computedHeaderCRC24 != readHeaderCRC24 {
+		return nil, false, fmt.Errorf("gocql: crc24 mismatch in frame header, computed: %d, got: %d", computedHeaderCRC24, readHeaderCRC24)
+	}
+
+	// Extract the payload length and self-contained flag
+	headerInt := binary.LittleEndian.Uint32(header[:4])
```
Comment (joao-r-reis) [inline frame.go]: Header size is only 3 bytes but we're passing a 4 byte slice which is confusing. 

`headerInt := uint32(header[0]) | uint32(header[1])<<8 | uint32(header[2])<<16`

File: frame.go [hunk 30]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+	payloadLen := int(headerInt & 0x1FFFF)
```
Comment (joao-r-reis) [inline frame.go]: NIT: make `0x1FFFF` a constant (max segment payload size)

File: frame.go [hunk 31]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+	const headerSize = 6
+	header := [headerSize + 1]byte{}
+
+	// Read the frame header
+	if _, err := io.ReadFull(r, header[:headerSize]); err != nil {
+		return nil, false, fmt.Errorf("gocql: failed to read uncompressed frame, err: %w", err)
+	}
+
+	// Compute and verify the header CRC24
+	computedHeaderCRC24 := KoopmanChecksum(header[:3])
```
Comment (joao-r-reis) [inline frame.go]: NIT: `KoopmanChecksum(header[:headerSize])`

File: frame.go [hunk 32]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+	isSelfContained := (headerInt & (1 << 17)) != 0
+
+	// Read the payload
+	payload := make([]byte, payloadLen)
+	if _, err := io.ReadFull(r, payload); err != nil {
+		return nil, false, fmt.Errorf("gocql: failed to read uncompressed frame payload, err: %w", err)
+	}
+
+	// Read and verify the payload CRC32
+	if _, err := io.ReadFull(r, header[:4]); err != nil {
```
Comment (joao-r-reis) [inline frame.go]: NIT: make `4` a constant (crc32 length), `io.ReadFull(r, header[:crc32Size])`

File: frame.go [hunk 33]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+	}
+
+	adjustedBuf = append(adjustedBuf, tempBuf...)
+	f.buf = adjustedBuf
+
+	return nil
+}
+
+func readUncompressedFrame(r io.Reader) ([]byte, bool, error) {
+	const headerSize = 6
```
Comment (joao-r-reis) [inline frame.go]: NIT: I'd say put this as `3` and add a constant for `crc24Size`

File: frame.go [hunk 34]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+	header := [headerSize + 1]byte{}
```
Comment (joao-r-reis) [inline frame.go]: NIT: `headerBuf := [headerSize + crc24Size]byte{}`

File: frame.go [hunk 35]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+
+	// Read the frame header
+	if _, err := io.ReadFull(r, header[:headerSize]); err != nil {
```
Comment (joao-r-reis) [inline frame.go]: `io.ReadFull(r, header[:])` after making the array size of `6` instead of `7` (see comment below)

File: frame.go [hunk 36]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+		return nil, false, fmt.Errorf("gocql: failed to read uncompressed frame payload, err: %w", err)
+	}
+
+	// Read and verify the payload CRC32
+	if _, err := io.ReadFull(r, header[:4]); err != nil {
+		return nil, false, fmt.Errorf("gocql: failed to read payload crc32, err: %w", err)
+	}
+
+	computedPayloadCRC32 := ChecksumIEEE(payload)
+	readPayloadCRC32 := binary.LittleEndian.Uint32(header[:4])
```
Comment (joao-r-reis) [inline frame.go]: NIT `binary.LittleEndian.Uint32(header[:crc32Size])`

File: frame.go [hunk 37]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+	// Compute and write the CRC32 checksum of the payload
+	payloadChecksum := ChecksumIEEE(compressedPayload)
+	binary.LittleEndian.PutUint32(headerBuf[:], payloadChecksum)
+	buf.Write(headerBuf[:4])
+
+	return buf.Bytes(), nil
+}
+
+func readCompressedFrame(r io.Reader, compressor Compressor) ([]byte, bool, error) {
+	var (
```
Comment (joao-r-reis) [inline frame.go:2335]: NIT: add constants: `headerSize = 5`, `crc24Size = 3`

File: frame.go [hunk 38]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+		err       error
+	)
+
+	if _, err = io.ReadFull(r, headerBuf[:]); err != nil {
+		return nil, false, err
+	}
+
+	// Reading checksum from frame header
+	readHeaderChecksum := uint32(headerBuf[5]) | uint32(headerBuf[6])<<8 | uint32(headerBuf[7])<<16
+	if computedHeaderChecksum := KoopmanChecksum(headerBuf[:5]); computedHeaderChecksum != readHeaderChecksum {
```
Comment (joao-r-reis) [inline frame.go]: NIT: `KoopmanChecksum(headerBuf[:headerSize]);`

File: go.mod [hunk 39]
```diff
@@ -20,11 +20,14 @@ module github.com/gocql/gocql
...
 	github.com/hailocab/go-hostpool v0.0.0-20160125115350-e80d13ce29ed
 	github.com/kr/pretty v0.1.0 // indirect
-	github.com/stretchr/testify v1.3.0 // indirect
+	github.com/stretchr/testify v1.9.0
 	gopkg.in/inf.v0 v0.9.1
 )
 
 go 1.13
+
+replace github.com/gocql/gocql/lz4 => ./lz4
```
Comment (joao-r-reis) [inline go.mod]: This doesn't seem intended?

File: go.mod [hunk 40]
```diff
@@ -20,11 +20,14 @@ module github.com/gocql/gocql
 require (
 	github.com/bitly/go-hostpool v0.0.0-20171023180738-a3a6125de932 // indirect
 	github.com/bmizerany/assert v0.0.0-20160611221934-b7ed37b82869 // indirect
+	github.com/gocql/gocql/lz4 v0.0.0-20240925165811-953e0df999ca
```
Comment (joao-r-reis) [inline go.mod]: This doesn't seem intended?

File: frame.go [hunk 41]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+
+	// Self-contained flag
+	selfContained := (headerBuf[4] & 0b100) != 0
+
+	compressedPayload := make([]byte, compressedLen)
+	if _, err = io.ReadFull(r, compressedPayload); err != nil {
+		return nil, false, fmt.Errorf("gocql: failed to read compressed frame payload, err: %w", err)
+	}
+
+	if _, err = io.ReadFull(r, headerBuf[:4]); err != nil {
```
Comment (joao-r-reis) [inline frame.go]: NIT: `io.ReadFull(r, headerBuf[:crc32Size])`

File: frame.go [hunk 42]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+		return nil, false, fmt.Errorf("gocql: failed to read payload crc32, err: %w", err)
+	}
+
+	// Ensuring if payload checksum matches
+	readPayloadChecksum := binary.LittleEndian.Uint32(headerBuf[:4])
```
Comment (joao-r-reis) [inline frame.go]: NIT: `binary.LittleEndian.Uint32(headerBuf[:crc32Size])`

File: conn_test.go [hunk 43]
```diff
@@ -1300,3 +1301,96 @@ func (srv *TestServer) readFrame(conn net.Conn) (*framer, error) {
 
 	return framer, nil
 }
+
+func TestConnProcessAllEnvelopesInSingleFrame(t *testing.T) {
```
Comment (joao-r-reis) [inline conn_test.go]: `TestConnProcessAllFramesInSingleSegment`

File: conn.go [hunk 44]
```diff
@@ -1086,7 +1155,29 @@ func (c *Conn) exec(ctx context.Context, req frameBuilder, tracer Tracer) (*fram
 		return nil, err
 	}
 
-	n, err := c.w.writeContext(ctx, framer.buf)
+	var n int
+
+	if c.version > protoVersion4 && startupCompleted {
+		err = framer.prepareModernLayout()
+		if err != nil {
```
Comment (joao-r-reis) [inline conn.go]: Do we need this `if` here? Can't we just check below before calling `c.w.writeContext` and let that error handling code do this for us?
```
if err == nil {
    n, err = c.w.writeContext(ctx, framer.buf)
}
if err != nil {
// existing error handling
}
```

File: frame.go [hunk 45]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+
+func newUncompressedFrame(payload []byte, isSelfContained bool) ([]byte, error) {
+	const (
+		headerSize       = 6
+		selfContainedBit = 1 << 17
+	)
+
+	payloadLen := len(payload)
+	if payloadLen > maxPayloadSize {
+		return nil, fmt.Errorf("payload length (%d) exceeds maximum size of 128 KiB", payloadLen)
```
Comment (joao-r-reis) [inline frame.go]: NIT: use the constant for the maximum payload size in the string

File: frame.go [hunk 46]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+	}
+
+	// Create the frame
+	frameSize := headerSize + payloadLen + 4 // 4 bytes for CRC32
+	frame := make([]byte, frameSize)
```
Comment (joao-r-reis) [inline frame.go]:
```
        // Create the frame
	segmentSize := headerSize + payloadLen + crc32Size
	segment := make([]byte, segmentSize)
```

File: frame.go [hunk 47]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+		return nil, fmt.Errorf("uncompressed compressed payload length exceedes max size of frame payload %d/%d", uncompressedLen, maxPayloadSize)
+	}
+
+	compressedPayload, err := compressor.Encode(uncompressedPayload)
+	if err != nil {
+		return nil, err
+	}
+
+	// Skip the first 4 bytes because the size of the uncompressed payload is written in the frame header, not in the
+	// body of the compressed envelope
```
Comment (joao-r-reis) [inline frame.go]:
```
// Skip the first 4 bytes because the size of the uncompressed payload is written in the segment header, not in the
// body of the compressed frame
```

File: frame.go [hunk 48]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+		combined |= 1 << 34
+	}
+
+	var headerBuf [8]byte
+
+	// Write the combined value into the header buffer
+	binary.LittleEndian.PutUint64(headerBuf[:], combined)
+
+	// Create a buffer with enough capacity to hold the header, compressed payload, and checksums
+	buf := bytes.NewBuffer(make([]byte, 0, 8+compressedLen+4))
```
Comment (joao-r-reis) [inline frame.go]: NIT:  `buf := bytes.NewBuffer(make([]byte, 0, headerSize + crc24Size + compressedLen + crc32Size))`

File: frame.go [hunk 49]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+
+	// Write the first 5 bytes of the header (compressed and uncompressed sizes)
+	buf.Write(headerBuf[:5])
```
Comment (joao-r-reis) [inline frame.go]: NIT: `buf.Write(headerBuf[:headerSize])`

File: frame.go [hunk 50]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+		uncompressedLen = 0
+	}
+
+	// Combine compressed and uncompressed lengths and set the self-contained flag if needed
+	combined := uint64(compressedLen) | uint64(uncompressedLen)<<17
+	if isSelfContained {
+		combined |= 1 << 34
+	}
+
+	var headerBuf [8]byte
```
Comment (joao-r-reis) [inline frame.go]: NIT: `var headerBuf [headerSize + crc24Size]byte`

File: frame.go [hunk 51]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+	binary.LittleEndian.PutUint64(headerBuf[:], combined)
+
+	// Create a buffer with enough capacity to hold the header, compressed payload, and checksums
+	buf := bytes.NewBuffer(make([]byte, 0, 8+compressedLen+4))
+
+	// Write the first 5 bytes of the header (compressed and uncompressed sizes)
+	buf.Write(headerBuf[:5])
+
+	// Compute and write the CRC24 checksum of the first 5 bytes
+	headerChecksum := KoopmanChecksum(headerBuf[:5])
```
Comment (joao-r-reis) [inline frame.go]: NIT: `headerChecksum := KoopmanChecksum(headerBuf[:headerSize])`

File: frame.go [hunk 52]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+	binary.LittleEndian.PutUint32(headerBuf[:], headerChecksum)
+	buf.Write(headerBuf[:3])
```
Comment (joao-r-reis) [inline frame.go:2321]: Hmm this works but it is a bit confusing (`PutUint32` but then we only write 24 bits). How about:
```
// LittleEndian 3 bytes
headerBuf[0] = byte(headerChecksum)
headerBuf[1] = byte(headerChecksum >> 8)
headerBuf[2] = byte(headerChecksum >> 16)
buf.Write(headerBuf[:3])
```

File: frame.go [hunk 53]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+	if payloadLen > maxPayloadSize {
+		return nil, fmt.Errorf("payload length (%d) exceeds maximum size of 128 KiB", payloadLen)
+	}
+
+	// Create the frame
+	frameSize := headerSize + payloadLen + 4 // 4 bytes for CRC32
+	frame := make([]byte, frameSize)
+
+	// First 3 bytes: payload length and self-contained flag
+	headerInt := uint32(payloadLen) & 0x1FFFF
```
Comment (joao-r-reis) [inline frame.go]: I don't think the `& 0x1FFFF` part is necessary since we already checked that this value is within the acceptable payload length.

File: frame.go [hunk 54]
```diff
@@ -2070,3 +2133,247 @@ func (f *framer) writeBytesMap(m map[string][]byte) {
...
+		if f.compres != nil {
+			tempBuf, err = newCompressedFrame(f.buf[:maxPayloadSize], false, f.compres)
+		} else {
+			tempBuf, err = newUncompressedFrame(f.buf[:maxPayloadSize], false)
+		}
+		if err != nil {
+			return err
+		}
+
+		adjustedBuf = append(adjustedBuf, tempBuf...)
```
Comment (joao-r-reis) [inline frame.go:2155]: I have some concerns about performance not being the best when compared to v4 but I don't think it will be bad enough to justify making it a blocker for this PR. It would be nice to get some benchmark data comparing the v4 and v5 implementations for the same workloads though.

**Review by joao-r-reis — COMMENTED** [review]
Most of my comments are NITs related to code readability. Feel free to close any of these specific ones that you don't agree with. The implementation itself looks very solid 👍

**Comment by worryg0d** [comment]
Once again I received this amount of feedback. Thanks a lot! I'm pleased to see how much attention you pay to this PR. I'm going to solve all of them ASAP

File: conn.go (hunk 16 above)
Comment (worryg0d) [reply conn.go]: I think `recvPartialFrames` is a more appropriate name. Thanks!

File: conn.go (hunk 17 above)
Comment (worryg0d) [reply conn.go]: Renamed to `frame`

File: conn.go (hunk 18 above)
Comment (worryg0d) [reply conn.go]: Renamed

File: conn.go (hunk 19 above)
Comment (worryg0d) [reply conn.go]: Renamed to `recvSegment`

File: crc.go (hunk 26 above)
Comment (worryg0d) [reply crc.go]: I renamed them to `Crc32` and `Crc24`

File: go.mod (hunk 39 above)
Comment (worryg0d) [reply go.mod]: Oops. I need it for testing and forgot to remove it. Thanks!

File: frame.go (hunk 30 above)
Comment (worryg0d) [reply frame.go]: Using `maxSegmentPayloadSize`

File: conn.go (hunk 44 above)
Comment (worryg0d) [reply conn.go]: Oh, that's a pretty good variant. I don't have to duplicate existing error handling, which I didn't like with my solution. Thanks a lot

File: frame.go (hunk 53 above)
Comment (worryg0d) [reply frame.go]: You have a point. Removed

File: conn.go (hunk 27 above)
Comment (worryg0d) [reply conn.go:681]: > This should be changed to r as well right?

You're right. I didn't notice it here.

> I think this is even the case on readUncompressedFrame and readCompressedFrame... It's using c.r directly but it should be using c so the additional logic from Conn.Read() is used right?

I didn't even notice that `Conn` implements `io.Reader`. I assumed that `*bufio.Reader` should be used to read from the socket because I had seen [line 673](https://github.com/apache/cassandra-gocql-driver/blob/953e0df999cabb3f5eef714df9921c00e9f632c2/conn.go#L673C1-L674C1) where `c.r` is used:
```
head, err := readHeader(c.r, c.headerBuf[:])
```

> I think we should create a type (maybe connReader?) that wraps the *bufio.Reader object and then move the implementation of Conn.Read() to that new type so we ensure that we only have one object that implements io.Reader. This way c.r becomes an object of *connReader instead of *bufio.Reader, Conn no longer implements io.Reader and everytime we want to actually read from the socket we have to use the c.r field instead of c directly.

Something like [this](https://github.com/worryg0d/gocql/commit/44cc2fc9f2344928f261d43c60071db1170d706c)? It makes sense since it forces us to use `c.r` instead of `Conn` itself. However, there is `net.Conn` still presented in `Conn`, which may be accidentally used instead.

File: frame.go (hunk 54 above)
Comment (worryg0d) [reply frame.go:2155]: Yeah, this is a weak spot of the implementation. I had an idea on in-place sending segments to C* instead of collecting them into a single buffer but it wasn't natural for the current codebase, so I decided to leave it as it is.
However, since we have agreed on Segments->NewFormatFrames and Frames->OldFormatFrames, then I could do this frame segmentation process on the `Conn` layer instead of the `framer`. You may look at the implementation [here](https://github.com/worryg0d/gocql/commit/4e1a7807dc4b6870a3df0bcf2166ef77e53a0330)

File: conn.go (hunk 15 above)
Comment (worryg0d) [reply conn.go]: It makes sense to add additional checks here. Added

File: conn.go (hunk 14 above)
Comment (worryg0d) [reply conn.go]: Yeah, it kinda makes sense to check if we're writing as much data as expected. Added a check for this too.

**Comment by worryg0d** [comment]
Hey, @joao-r-reis. I added changes to this PR according to your last review feedback. There are a lot of renames and improvements in the reading/writing segments part. Could you please look at this one again?
I liked all MIT suggestions and they are part of the PR now.

File: go.mod [hunk 55]
```diff
@@ -23,7 +23,7 @@ require (
 	github.com/golang/snappy v0.0.3
 	github.com/hailocab/go-hostpool v0.0.0-20160125115350-e80d13ce29ed
 	github.com/kr/pretty v0.1.0 // indirect
-	github.com/stretchr/testify v1.3.0 // indirect
+	github.com/stretchr/testify v1.9.0
```
Comment (joao-r-reis) [inline go.mod]: do we use this library directly? it used to be just an indirect dependency

File: frame.go (hunk 54 above)
Comment (joao-r-reis) [reply frame.go:2155]: Hmm that implementation has less allocations but it has an issue. If the request is large and "generates" multiple segments then it will wait until the write coalescer writes 1 segment before writing the next one.
I think we can keep the existing framer based implementation for now.

File: conn.go (hunk 27 above)
Comment (joao-r-reis) [reply conn.go:681]: > Something like [this](https://github.com/worryg0d/gocql/commit/44cc2fc9f2344928f261d43c60071db1170d706c)? It makes sense since it forces us to use c.r instead of Conn itself. However, there is net.Conn still presented in Conn, which may be accidentally used instead.

Yeah, we can go even further and completely move both `net.Conn` and `bufio.Reader` fields to a separate type that implements the `net.Conn` interface. the `timeout` field could also be removed from `gocql.Conn`. This way we ensure nobody uses the underlying `net.Conn` object directly by mistake.

```
type ConnWrapper interface {
    net.Conn
}

type connWrapper struct {
	conn      net.Conn
	r         *bufio.Reader
	timeout   time.Duration
}

func (c *connWrapper) Read(p []byte) (n int, err error) {
	const maxAttempts = 5
	for i := 0; i < maxAttempts; i++ {
		var nn int
		if c.timeout > 0 {
			c.SetReadDeadline(time.Now().Add(c.timeout))
		}
		nn, err = io.ReadFull(c.r, p[n:])
		n += nn
		if err == nil {
			break
		}
		if verr, ok := err.(net.Error); !ok || !verr.Temporary() {
			break
		}
	}
	return
}

// implement remaining net.Conn`functions by just delegating to c.conn
```

**Review by joao-r-reis — COMMENTED** [review]
Awesome stuff, I think the only remaining issue is the `net.Conn` / `bufio.Reader` discussion and other than that I think we're good. I'm going to ping the slack channel to see if we can get another committer to review this (we need 2 +1s from committers).

File: go.mod (hunk 55 above)
Comment (worryg0d) [reply go.mod]: I used sometimes both `require` and `assert` from `testify` in integration and unit tests

File: frame.go (hunk 54 above)
Comment (worryg0d) [reply frame.go:2155]: Oh, I didn't account for it. Yeah, sometimes we have to pay some price... Ok, let's leave it for now

File: conn.go (hunk 27 above)
Comment (worryg0d) [reply conn.go:681]: I updated the impl of [ConnReader](https://github.com/worryg0d/gocql/commit/bc29d6e491e75fd72f0c77445151dc117d62ac02). The only thing I don't like here is that [calling](https://github.com/worryg0d/gocql/blob/bc29d6e491e75fd72f0c77445151dc117d62ac02/conn.go#L567C1-L569C2) `Close()` on the `r` actually closes the whole `net.Conn`. We should probably move `contextWriter` from `Conn` to the wrapper as well...

File: compressor.go (hunk 4 above)
Comment (martin-sucha) [inline compressor.go]: Could you please add doc comment describing the semantics of the method?

<hr />

We could also change this to be append-like, as follows:

```go
// DecodeSized decodes the encoded bytes and appends them to dst.
// decodeSize is the size of data after decompression.
DecodeSized(dst, encoded []byte, decodedSize int32) ([]byte, error)
```

It seems that would be more flexible, for example it would allow the framer to reuse buffers for decompression in a sync.Pool if needed. And since this will be in 2.0, we could adjust the other methods as well.

File: conn.go (hunk 27 above)
Comment (joao-r-reis) [reply conn.go:681]: I like the implementation you linked 👍 .

> The only thing I don't like here is that [calling](https://github.com/worryg0d/gocql/blob/bc29d6e491e75fd72f0c77445151dc117d62ac02/conn.go#L567C1-L569C2) Close() on the r actually closes the whole net.Conn. We should probably move contextWriter from Conn to the wrapper as well...

Hmm this is the existing behavior though right? I'm focused mostly on keeping the same behavior with this refactoring unless there's something that we know for sure is incorrect. In this case I think closing the whole `net.Conn` in `close()` is fine, there's a check when writing to see if the connection is closed or not. 

One thing we can do is remove the lower case `Conn.close()` because at the moment we have a `Conn.Close()` and a `Conn.close()`. The lower case one is just confusing, the `Conn.Close()` function should just call `connReader.Close()` directly.

File: compressor.go (hunk 4 above)
Comment (joao-r-reis) [reply compressor.go]: I agree with this, it's a great suggestion 👍 We don't have to work on changing the framer to reuse buffers now but making the API change now on the 2.0 release would make the most sense.

File: conn.go (hunk 27 above)
Comment (worryg0d) [reply conn.go:681]: > Hmm this is the existing behavior though right?

Right, it calls close of underlying conn, so the behavior is not changed. It's just a bit confusing for me that calling `Close()` on `ConnReader` affects `writerContext` as well because they both use the same `net.Conn`.

> One thing we can do is remove the lower case Conn.close() because at the moment we have a Conn.Close() and a Conn.close(). The lower case one is just confusing, the Conn.Close() function should just call connReader.Close() 
directly.

I removed `Conn.close()` and added conn reader to this PR [a79c985](https://github.com/worryg0d/gocql/commit/a79c9853a50f2c6e2afc262be3a241e1bc1a97ff)

File: compressor.go (hunk 4 above)
Comment (worryg0d) [reply compressor.go]: Then we should agree on the API.

We could adjust the current API to [this](https://github.com/worryg0d/gocql/commit/b4e0322e2af541fa0a3b7c467802e20cfa691ef6):
```go
type Compressor interface {
	Name() string
	Encode(dst, data []byte) ([]byte, error)
	Decode(dst, data []byte) ([]byte, error)

	// DecodeSized decodes the encoded bytes and appends them to dst.
	// decodeSize is the size of data after decompression.
	DecodeSized(dst, encoded []byte, decodedSize uint32) ([]byte, error)
}
```

As another solution, we could change the API to this:
```go
type Compressor interface {
	Name() string
	
	// EncodeWithSize encodes data bytes, appends the size of the data
	// to dst and appends encoded bytes.
	// It returns encoded data length.
	EncodeWithSize(dst, data []byte) (n int, err error)
	
	// DecodeWithSize reads size of uncompressed data from the encoded data,
	// decodes the encoded bytes and appends them to dst.
	// It returns decoded data length.
	DecodeWithSize(dst, encoded []byte) (n int, err error)

	// Encode encodes data bytes and appends them to dst.
	// It returns encoded data length.
	Encode(dst, data []byte) (n int, err error)

	// Decode decodes the encoded bytes and appends them to dst.
	// It returns decoded data length.
	Decode(dst, encoded []byte) (n int, err error)
}
```

The second provides distinguishing methods for:
* **frame body** encoding/decoding `EncodeWithSize` and `DecodeWithSize`
* **segment payload** processing `Encode` and `Decode`.

Comment (joao-r-reis) [reply compressor.go]: To truly make it 100% "append-like" (examples: https://github.com/golang/go/issues/53693):

```
type Compressor interface {
	Name() string
	
	// AppendCompressedWithLength compresses src bytes, appends the length of the compressed bytes to dst and then appends the compressed bytes to dst.
        // It returns a new byte slice that is the result of the append operation.
	AppendCompressedWithLength(dst, src []byte) ([]byte, error)
	
	// AppendDecompressedWithLength reads the length of the decompressed bytes from src, decompresses bytes from src and appends the decompressed bytes to dst.
        // It returns a new byte slice that is the result of the append operation.
	AppendDecompressedWithLength(dst, src []byte) ([]byte, error)

	// AppendCompressed compresses src bytes and appends the compressed bytes to dst.
        // It returns a new byte slice that is the result of the append operation.
	AppendCompressed(dst, src []byte) ([]byte, error)

	// AppendDecompressed decompresses bytes from src and appends the decompressed bytes to dst.
        // It returns a new byte slice that is the result of the append operation.
	AppendDecompressed(dst, src []byte, decompressedLength uint32) ([]byte, error)
}
```

The lz4 library does not support append like semantics so we're going to have to expand `dst` slice before passing it to the lz4 library functions. If `cap(dst)-len(dst)` is not large enough then we'll have to allocate a new byte slice and append it to `dst` instead. `AppendDecompressed` has the `decompressedLength` parameter so we can check if we can reuse `dst` or if we have to allocate a new byte slice.

I used the name `Compress` and `Decompress` instead of `Encode` / `Decode` because it felt more natural to me but I'm fine with keeping `Encode` and `Decode`. Same for `WithLength`/`WithSize`

File: conn.go (hunk 27 above)
Comment (joao-r-reis) [reply conn.go:681]: Nice!

File: compressor.go (hunk 4 above)
Comment (worryg0d) [reply compressor.go]: Could you please look at [this](https://github.com/worryg0d/gocql/commit/53c721ff91de86f7f02f16eeeefc4a15a290ad22)? I tried to implement this append-like API, but I'm unsure if I should implement the `AppendCompressed` and `AppendDecompressed` methods for our snappy wrapper...

> I used the name Compress and Decompress instead of Encode / Decode because it felt more natural to me but I'm fine with keeping Encode and Decode. Same for WithLength/WithSize

I like your variants. If nobody has anything against then I'll use them.

Comment (joao-r-reis) [reply compressor.go]: Added a few comments but that's the spirit of what I was suggesting 👍  @martin-sucha can you also take a look to see if it is in line with what you were suggesting?

**Comment by joao-r-reis** [comment]
I'm going to work on updating the `CONTRIBUTING.md` file really quick but after that I'll get back to this PR and investigate the result metadata id issue.

File: compressor.go (hunk 4 above)
Comment (joao-r-reis) [reply compressor.go]: > I'm unsure if I should implement the AppendCompressed and AppendDecompressed methods for our snappy wrapper...

I think it's fine to make them panic since protocol v5 doesn't support snappy anyway.

Comment (worryg0d) [reply compressor.go]: I added the suggested by @joao-r-reis solution. @martin-sucha Could you please take a look at [this](https://github.com/apache/cassandra-gocql-driver/pull/1822/commits/86130c0836b49d3ad253725f8d9e837443afd7bd)?

File: frame_test.go (hunk 1 above)
Comment (joao-r-reis) [reply frame_test.go:135]: https://issues.apache.org/jira/browse/CASSANDRA-20028

File: conn.go (hunk 10 above)
Comment (joao-r-reis) [reply conn.go]: I'm unable to get C* to set the METADATA_CHANGED flag... I opened https://issues.apache.org/jira/browse/CASSANDRA-20028 to track this. Meanwhile we are unable to test this so it's a bit risky to merge it (if C* fixes this in a new version then existing gocql users who may have upgraded to get v5 support might start seeing errors).

File: conn.go (hunk 11 above)
Comment (joao-r-reis) [reply conn.go]: So we are unable to test this for now (see my [earlier comment](https://github.com/apache/cassandra-gocql-driver/pull/1822#discussion_r1816923792)), but we can still try to implement it according to the v5 spec. 

The expected implementation is that the driver will parse the new metadata from the `ROWS` response and update the local prepared statement object with the new result metadata AND result metadata id. Since the new up to date metadata is included in the response the driver has everything it needs to parse the response without another round trip and no new round trip should occur.

File: frame.go [hunk 56]
```diff
@@ -1060,6 +1068,10 @@ func (f *framer) parseResultMetadata() resultMetadata {
 		meta.pagingState = copyBytes(f.readBytes())
 	}
 
+	if meta.flags&flagMetaDataChanged == flagMetaDataChanged {
+		meta.newMetadataID = copyBytes(f.readBytes())
```
Comment (joao-r-reis) [inline frame.go]: we should only check this flag if protoversion is `> 4`. Also the result metadata id is a `[short bytes]` not `[bytes]` (see how it is being parsed in the `PREPARED` response and the v5 spec)

File: conn.go (hunk 10 above)
Comment (worryg0d) [reply conn.go]: That's a shame... I hope anybody from ASF will help us with this one.

> Meanwhile we are unable to test this so it's a bit risky to merge it 

I agree with you, a test lacking implementation is risky, I have to do something with this...

File: frame.go (hunk 56 above)
Comment (worryg0d) [reply frame.go]: Good catch! And this is what tests lacking is leading to...

File: conn.go (hunk 11 above)
Comment (worryg0d) [reply conn.go]: So, we're expecting that when `<new_metadata_id>` is presented in **ROWS/RESULT** response the driver should update its cache to include the updated result metadata set and new `<result_metadata_id>` for subsequent executions and return the result. 
If `<new_metadata_id>` is presented in response, but the stmts cache doesn't contain the corresponding prepared stmt, the driver should return the result only.

Comment (joao-r-reis) [reply conn.go]: > So, we're expecting that when <new_metadata_id> is presented in ROWS/RESULT response the driver should update its cache to include the updated result metadata set and new <result_metadata_id> for subsequent executions and return the result.
If <new_metadata_id> is presented in response, but the stmts cache doesn't contain the corresponding prepared stmt, the driver should return the result only.

+1

Comment (joao-r-reis) [reply conn.go]: ok I found a way to trigger the `NEW_METADATA_ID` flag in the response but you basically have to add temporary code to make the driver NOT update the prepared entry when it receives an UNPREPARED, this is obviously not how it should work but it's a way to at least do some manual testing to make sure this flow is working properly.

In `Conn.executeQuery` replace the whole `case *RequestErrUnprepared` block with this:

```
case *RequestErrUnprepared:
		stmtCacheKey := c.session.stmtsLRU.keyFor(c.host.HostID(), c.currentKeyspace, qry.stmt)
		prep := &writePrepareFrame{
			statement: qry.stmt,
		}
		if c.version > protoVersion4 {
			prep.keyspace = qry.keyspace
		}

		framer, err := c.exec(c.ctx, prep, qry.trace)
		if err != nil {
			c.session.stmtsLRU.remove(stmtCacheKey)
			return &Iter{err: x, framer: framer}
		}

		_, err = framer.parseFrame()
		if err != nil {
			c.session.stmtsLRU.remove(stmtCacheKey)
			return &Iter{err: x, framer: framer}
		}
		return c.executeQuery(ctx, qry)
```
This will cause gocql to send an `EXECUTE` with the old result metadata ID even after the RE-PREPARE which will then cause C* to return `ROWS` with the new metadata. This happens because with this code gocql will send a PREPARE after the UNPREPARED response but it will keep using the old entry in the cache (because it's not being evicted). This is only for test purposes! Obviously the existing behavior (evicting from the cache and re-preparing) is the correct one but it's not letting us test the new flag 😅

File: conn.go [hunk 57]
```diff
@@ -1430,6 +1612,34 @@ func (c *Conn) executeQuery(ctx context.Context, qry *Query) *Iter {
...
+
+			newInflight := &inflightPrepare{
+				done: make(chan struct{}),
+				preparedStatment: &preparedStatment{
+					id:               oldInflight.preparedStatment.id,
+					resultMetadataID: x.meta.newMetadataID,
+					request:          oldInflight.preparedStatment.request,
+					response:         x.meta,
+				},
+			}
```
Comment (joao-r-reis) [inline conn.go:1629]: This causes a deadlock because the `done` channel will never be closed so the goroutine will be stuck trying to read from it.
I think you're already in the process of fixing this flow according to [your comment here](https://github.com/apache/cassandra-gocql-driver/pull/1822/files#r1817022382) but I did find this so I figured I'd point it out regardless.

Comment (worryg0d) [reply conn.go:1629]: Oh... I forgot to close this `done` after adding a new inflight to the cache... But it will look a bit weird to me... However, using the old one `done` here is not a solution because there won't be a guarantee that the updated metadata is used by other goroutines.

File: conn.go (hunk 11 above)
Comment (worryg0d) [reply conn.go]: Awesome! I can test the whole metadata_changed flow with this one. Thanks a lot!

File: conn.go (hunk 57 above)
Comment (joao-r-reis) [reply conn.go:1629]: Yeah it's fine to create the channel and close it right away, it might look a bit weird but it's the only way to make this work unless we change how the ps cache works.

File: conn.go (hunk 11 above)
Comment (worryg0d) [reply conn.go]: I wrote an [integration test](https://github.com/worryg0d/gocql/commit/9717fa551bb05e1d088ce1defb3159dd5a299af5) for this mechanism. Could you please take a look at it to ensure that I didn't miss something?

Also, I figured out that the driver still uses old metadata when `skipMeta` is set. According to the specification, the driver should ignore it when the `Metadata_changed` flag is set, right?
```
            0x0008    Metadata_changed: if set, the No_metadata flag has to be unset
                      and <new_metadata_id> has to be supplied. This flag is to be
                      used to avoid a roundtrip in case of metadata changes for queries
                      that requested metadata to be skipped.
```

Comment (joao-r-reis) [reply conn.go]: The driver should prioritize the metadata from the response if it exists before using the metadata from the prepared statement object regardless of whether the request had the skip metadata flag set or not. 

Just to clarify that part of the spec that you quoted refers to the `NO_METADATA` flag on the *response* not the `SKIP_METADATA` flag on the *request*. The gocql driver always assumes the rows response doesn't have the metadata (i.e. `NO_METADATA` is set) when the `SKIP_METADATA` flag was set on the request but we should remove that assumption 👍

Comment (worryg0d) [reply conn.go]: I added an integration test for this mechanism. Could you please review it [2a5056d](https://github.com/apache/cassandra-gocql-driver/pull/1822/commits/2a5056d6b1d1d479ca5ee97ddd1d95a9d8e8c4e2)?

File: conn.go [hunk 58]
```diff
@@ -1430,13 +1612,36 @@ func (c *Conn) executeQuery(ctx context.Context, qry *Query) *Iter {
...
+						id:               oldInflight.preparedStatment.id,
+						resultMetadataID: x.meta.newMetadataID,
+						request:          oldInflight.preparedStatment.request,
+						response:         x.meta,
+					},
+				}
+				c.session.stmtsLRU.add(stmtCacheKey, newInflight)
+				// The driver should close this done to avoid deadlocks of
+				// other subsequent requests
+				close(newInflight.done)
```
Comment (joao-r-reis) [inline conn.go:1624]: close it before even adding it to the cache, could potentially reduce blocking if another goroutine gets this stmt from the cache before the channel is closed

File: conn.go [hunk 59]
```diff
@@ -1430,13 +1612,36 @@ func (c *Conn) executeQuery(ctx context.Context, qry *Query) *Iter {
...
+		}
+
 		iter := &Iter{
 			meta:    x.meta,
 			framer:  framer,
 			numRows: x.numRows,
 		}
 
-		if params.skipMeta {
+		if params.skipMeta && x.meta.noMetaData() {
```
Comment (joao-r-reis) [inline conn.go]: I'd remove `params.skipMeta` from this check completely. If response has metadata we use it, if it doesn't have it then we use the metadata from the cache. The request flag doesn't even matter

File: conn.go [hunk 60]
```diff
@@ -1430,13 +1612,36 @@ func (c *Conn) executeQuery(ctx context.Context, qry *Query) *Iter {
...
+				newInflight := &inflightPrepare{
+					done: make(chan struct{}),
+					preparedStatment: &preparedStatment{
+						id:               oldInflight.preparedStatment.id,
+						resultMetadataID: x.meta.newMetadataID,
+						request:          oldInflight.preparedStatment.request,
+						response:         x.meta,
+					},
+				}
+				c.session.stmtsLRU.add(stmtCacheKey, newInflight)
```
Comment (joao-r-reis) [inline conn.go]: Update the `info` local variable here just in case so we ensure that the code in this function is looking at the updated version of the prepared statement.

File: conn.go (hunk 11 above)
Comment (joao-r-reis) [reply conn.go]: The test isn't triggering the METADATA_CHANGED flag atm because of what I mentioned before but here's a way that it can be changed to trigger it: https://github.com/joao-r-reis/gocql/commit/bf39830147873c52e825c10f3855538778f3b92f 

One thing that is missing from the test though is checking result data integrity after the metadata change. Maybe inserting a row after the ALTER with data on both columns and then asserting that the data retrieved matches the values we just inserted.

File: conn.go (hunk 12 above)
Comment (joao-r-reis) [reply conn.go:349]: I'm going to keep this one open until we have a second reviewer to look at this.

**Review by joao-r-reis — COMMENTED** [review]
Almost there! I think the functionality is now done and everything looks to be working correctly 👍 These last few comments are small things.

Still need another committer to take a look at this PR though.

File: conn.go [hunk 61]
```diff
@@ -1347,7 +1527,8 @@ func (c *Conn) executeQuery(ctx context.Context, qry *Query) *Iter {
 		params.pageSize = qry.pageSize
 	}
 	if c.version > protoVersion4 {
-		params.keyspace = c.currentKeyspace
+		params.keyspace = qry.keyspace
```
Comment (joao-r-reis) [inline conn.go:1510]: I just realized that we're still using `c.currentkeyspace` in the prepared statement cache key, if the user provides a different keyspace then we have to use that one. This is happening in `executeQuery`, `executeBatch`, `prepareStatementForKeyspace`. These are the ones I managed to catch. Idk if it is easy to write a test for this

Comment (joao-r-reis) [reply conn.go:1510]: You can probably catch this bug if you use the same query string on 2 statements but one of them you call `SetKeyspace`, if I'm correct both statements will internally use the same prepared statement and will go towards the same keyspace (I didn't test this, I'm speculating purely from reading the code).

**Comment by joao-r-reis** [comment]
Added `semver-major` label due to the Compressor interface changes

File: conn.go (hunk 61 above)
Comment (worryg0d) [reply conn.go:1510]: This is a very good catch. The driver should use the bounded keyspace of the stmt. At this moment, the key contains `c.currentKeyspace` which is the initial keyspace specified at `Cluster.Keyspace` and it looks like this:
```
Cluster.Keyspace = "__INITIAL_KS__"

98267857-1640-4054-92a1-9d214745ba9e__INITIAL_KS__SELECT * FROM gocql_test.keyspace_bug
```

I'm proposing to change this a bit to use keyspace in a cache key only when the QUERY/BATCH has an overridden keyspace (e.g. `SetKeyspace`).

So, if the query has an overridden keyspace the stmt cache key would look like this:
```
session.Query("SELECT * FROM gocql_test.keyspace_bug").SetKeyspace("__OVERRIDEN_KEYSPACE__")

98267857-1640-4054-92a1-9d214745ba9e__OVERRIDEN_KEYSPACE__SELECT * FROM gocql_test.keyspace_bug
```

If there is no overridden keyspace for the query, the keyspace won't be presented in the stmt key:
```
session.Query("SELECT * FROM gocql_test.keyspace_bug")

98267857-1640-4054-92a1-9d214745ba9eSELECT * FROM gocql_test.keyspace_bug
```

Also, I found that `routingKeyInfo` also uses `c.current` keyspace and this place is a bit tricky for me. I can just make it to take a keyspace, but I'm not sure how it lines with the purpose of this method...

And one more thing, if we agree on the proposal, we should get rid of `c.currentKeyspace`.

File: conn.go (hunk 58 above)
Comment (worryg0d) [reply conn.go:1624]: Even a little block is not very good here. Changed.

File: conn.go (hunk 59 above)
Comment (worryg0d) [reply conn.go]: And this one makes sense too because the driver should rely only on the response form C*. Fixed

File: conn.go (hunk 60 above)
Comment (worryg0d) [reply conn.go]: It looks like `info` is only used when there is no metadata in the response. However, it won't hurt to prevent this. Changed

File: conn.go (hunk 11 above)
Comment (worryg0d) [reply conn.go]: Awesome! I like the idea of changing the cache to force the driver to send queries with old metadata. Thank you!

> One thing that is missing from the test though is checking result data integrity after the metadata change

I added this to the test

File: conn.go (hunk 61 above)
Comment (joao-r-reis) [reply conn.go:1510]: > If there is no overridden keyspace for the query, the keyspace won't be presented in the stmt key:

Hmm I wonder what happens if you change the bounded keyspace on the connection and reuse the prepared statement that was prepared before the keyspace change? If C* uses the keyspace at the time of the PREPARE then this will not work (since gocql internally prepares automatically and the user might not even know this is happening).

Comment (joao-r-reis) [reply conn.go:1510]: I think we have to use `c.currentkeyspace` in the cache key if the keyspace wasn't set on the request.

Comment (worryg0d) [reply conn.go:1510]: > if you change the bounded keyspace on the connection

As far as I see gocql doesn't expose an API to change the bounded keyspace for the connection. The only place I see where initialized `Conn` is exposed is `HandleErorrHandler.HandleError` which is not meant to be used this way (?). However, there is still a possibility to call `Conn.UseKeyspace`...

Then we could just use the bounded keyspace if it is present, and when it is not we have to use `c.currentKeyspace`.

Comment (joao-r-reis) [reply conn.go:1510]: Hmm yeah it's true that gocql doesn't expose an API and it also tries to prohibit `USE` statements but it's quite easy to "trick" gocql into allowing it by just adding spaces before `USE` or through clever use of `;`.

> However, there is still a possibility to call Conn.UseKeyspace.

It's a bit weird to me that the `Conn` type has exported functions like that but that's a conversation for another time 😅

Comment (worryg0d) [reply conn.go:1510]: I changed the flow of construction stmt cache keys to account for the bound to the query keyspace. Also, `Session.routingKeyInfo()` was facing the same bug with the routing key info cache, so I changed it as well.
I added this to the PR with integration tests.

Comment (joao-r-reis) [reply conn.go:1510]: Hmm this prompted me to look a bit further into the routing key info and I think there's a couple of places where we are using the keyspace from the prepared metadata without any fallback but there's no guarantee that the metadata will have that keyspace field populated.

[Here](https://github.com/worryg0d/gocql/blob/b5d76bd04c9f32207554dd27f7cb6369423f5365/conn.go#L1589) we can set it to `usedKeyspace` if `info.request.keyspace == ""`

[And here](https://github.com/worryg0d/gocql/blob/b5d76bd04c9f32207554dd27f7cb6369423f5365/session.go#L663) we can set it to `keyspace` if `info.request.keyspace == ""`

On a separate note I think we're also missing a check if keyspace was set on the query [here](https://github.com/worryg0d/gocql/blob/b5d76bd04c9f32207554dd27f7cb6369423f5365/session.go#L1151-L1165), it should take precedence over the one from the `cfg`:

```
	if q.getKeyspace != nil {
		return q.getKeyspace()
	}
	if q.routingInfo.keyspace != "" {
		return q.routingInfo.keyspace
	}
        if q.keyspace != "" {
                return q.keyspace
        }

	if q.session == nil {
		return ""
	}
	// TODO(chbannis): this should be parsed from the query or we should let
	// this be set by users.
	return q.session.cfg.Keyspace
```

Comment (worryg0d) [reply conn.go:1510]: It's unclear when the `<global_table_spec>` flag is set in response to **PREPARE**. When I was testing this behavior C* always responded with this flag on stmt prepare requests. However, it wouldn't if we double-check this. I added this to the last commit.

**Review by joao-r-reis — APPROVED** [review]
Good stuff 👍 , I left 2 conversations open so that we get input from the other committer that looks at this:
- bumping `go.mod` version to `1.19` so we can use `atomic.Bool` (current minimum version is `1.17` but `go.mod` is not up to date
- Compressor interface changes

I'm +1 on both of these though.

**Comment by joao-r-reis** [comment]
oh I just noticed the integration tests on GH are running with `snappy` compression, we should change it to `lz4` so we get coverage on compression+v5

**Comment by worryg0d** [comment]
> Good stuff 👍 , I left 2 conversations open so that we get input from the other committer that looks at this:
> 
> * bumping `go.mod` version to `1.19` so we can use `atomic.Bool` (current minimum version is `1.17` but `go.mod` is not up to date
> * Compressor interface changes
> 
> I'm +1 on both of these though.

Thanks a lot! I'm really happy to hear that. I'm waiting for a review from another committer and hoping everything will be fine here.

> oh I just noticed the integration tests on GH are running with `snappy` compression, we should change it to `lz4` so we get coverage on compression+v5

Oh, yeah. I'll try to change CI to run tests here.

**Comment by worryg0d** [comment]
I changed CI [here](https://github.com/worryg0d/gocql/pull/11) to run tests over proto 5. One thing I had to replace `lz4` dependency in `go.mod` to use the updated version of the pkg...

**Comment by joao-r-reis** [comment]
Hmm it does look weird to have `gocql`'s `go.mod` list `gocql/lz4` as a dependency when `gocql/lz4`'s `go.mod` lists `gocql` as a dependency... A possible solution is to make `lz4` a package instead of its own module, I brought this up in slack and [here](https://github.com/apache/cassandra-gocql-driver/pull/1770#issuecomment-2451102573).

If `lz4` stays a separate module then I'm not sure what is the best way to use `lz4` in the integration tests... Maybe your approach is the best one, if I'm not mistaken the `lz4` dependency will not actually be downloaded by users since it's only used in tests.

File: go.mod [hunk 62]
```diff
@@ -23,7 +23,7 @@ require (
 	github.com/golang/snappy v0.0.3
```
Comment (joao-r-reis) [inline go.mod]: leaving a comment here as a reminder to bump the version to `1.17` or `1.19` if we keep `atomic.Bool` (actually you could probably make this `1.19` already to be consistent with the changes that are already in place

Comment (worryg0d) [reply go.mod]: I bumped the Go version to `1.19` and added it to the PR

**Review by ribaraka — APPROVED** [review]
lgtm

**Comment by worryg0d** [comment]
@joao-r-reis I adjusted the CI in this PR to run integration tests over proto 5 and the lz4 compressor. Could you please approve running the workflow to see if nothing breaks?

**Review by testisnullus — APPROVED** [review]

File: conn.go (hunk 12 above)
Comment (jameshartig) [reply conn.go:349]: I think forcing 1.19 is fine.

File: conn.go [hunk 63]
```diff
@@ -777,6 +774,172 @@ func (c *Conn) handleTimeout() {
...
+
+	// SetTimeout sets timeout duration for reading data form conn
+	SetTimeout(timeout time.Duration)
+
+	// GetTimeout returns timeout duration
+	GetTimeout() time.Duration
+}
+
+// connReader implements ConnReader.
+// It retries to read data up to 5 times or returns error.
```
Comment (jameshartig) [inline conn.go:861]: I'm curious why it retries up to 5 times. Is that recommended somewhere or consistent with other drivers? I'm not used to seeing a `Read` call not respect the timeout and instead take 5x the timeout.

File: go.mod [hunk 64]
```diff
@@ -18,13 +18,23 @@
 module github.com/gocql/gocql
```
Comment (jameshartig) [inline go.mod:19]: We should add `go 1.19` to this

File: conn.go [hunk 65]
```diff
@@ -1394,14 +1578,18 @@ func (c *Conn) executeQuery(ctx context.Context, qry *Query) *Iter {
 		params.skipMeta = !(c.session.cfg.DisableSkipMetadata || qry.disableSkipMetadata)
```
Comment (jameshartig) [inline conn.go]: Can you update this like I did in #1852 or we can just merge that MR since I don't think it'll conflict? We shouldn't be sending skipMeta if we didn't get it from the prepare. @joao-r-reis

Comment (joao-r-reis) [reply conn.go]: Yeah now I see the difference, I think it's better if we just merge #1852 right away, I don't think it will conflict

File: conn.go (hunk 63 above)
Comment (worryg0d) [reply conn.go:861]: Here I focused on extracting this [code](https://github.com/apache/cassandra-gocql-driver/blob/8bb171c2edfc696f96dc99c8db3499742d69db13/conn.go#L329) to the specific `connReader` type to avoid unintentional reading from `Conn.conn` or `Conn.r`. I didn't aim to change this behavior, because this is a bit out of the scope of this PR. However, I already added a `connReader`... Probably changing this behavior should be handled here as well

File: conn.go (hunk 65 above)
Comment (worryg0d) [reply conn.go]: I think we can merge #1852. It should not cause conflicts, but if it does I'll resolve them

**Comment by worryg0d** [comment]
Hello. This PR has already been floating for quite a while. Is there anything I can do to push it forward?

**Comment by joao-r-reis** [comment]
> Hello. This PR has already been floating for quite a while. Is there anything I can do to push it forward?

I'd like to get a +1 from another committer before merging this one because of its size. I think @jameshartig will take a look soon

File: conn.go [hunk 66]
```diff
@@ -777,6 +774,172 @@ func (c *Conn) handleTimeout() {
...
+// If Conn.compressor is not nil, it processes Compressed Format segments.
+func (c *Conn) recvPartialFrames(dst *bytes.Buffer, bytesToRead int) error {
+	var (
+		read            int
+		frame           []byte
+		isSelfContained bool
+		err             error
+	)
+
+	for read != bytesToRead {
```
Comment (jameshartig) [inline conn.go:813]: should this be `read < bytesToRead`? Is it possible to over-read?

File: go.mod [hunk 67]
```diff
@@ -18,13 +18,23 @@
...
+	github.com/bitly/go-hostpool v0.0.0-20171023180738-a3a6125de932 // indirect
+	github.com/bmizerany/assert v0.0.0-20160611221934-b7ed37b82869 // indirect
+	github.com/davecgh/go-spew v1.1.1 // indirect
+	github.com/kr/pretty v0.1.0 // indirect
+	github.com/pierrec/lz4/v4 v4.1.8 // indirect
+	github.com/pmezard/go-difflib v1.0.0 // indirect
+	gopkg.in/yaml.v3 v3.0.1 // indirect
+)
+
+replace github.com/gocql/gocql/lz4 => ./lz4
```
Comment (jameshartig) [inline go.mod]: I don't think this is needed. Go should know what the module is based on the module line.

File: .github/workflows/main.yml [hunk 68]
```diff
@@ -101,7 +101,7 @@ jobs:
           ccm status
           ccm node1 nodetool status
 
-          args="-gocql.timeout=60s -runssl -proto=4 -rf=3 -clusterSize=3 -autowait=2000ms -compressor=${{ matrix.compressor }} -gocql.cversion=$VERSION -cluster=$(ccm liveset) ./..."
+          args="-gocql.timeout=60s -runssl -proto=5 -rf=3 -clusterSize=3 -autowait=2000ms -compressor=${{ matrix.compressor }} -gocql.cversion=$VERSION -cluster=$(ccm liveset) ./..."
```
Comment (jameshartig) [inline .github/workflows/main.yml]: Should we be updating the matrix to test protocol version 4 and 5? Same thing about the next one too.

File: .github/workflows/main.yml [hunk 69]
```diff
@@ -37,7 +37,7 @@ jobs:
         go: [ '1.22', '1.23' ]
         cassandra_version: [ '4.0.13', '4.1.6' ]
         auth: [ "false" ]
-        compressor: [ "snappy" ]
+        compressor: [ "lz4" ]
```
Comment (jameshartig) [inline .github/workflows/main.yml]: Should we be testing snappy and lz4?

**Comment by jameshartig** [comment]
@worryg0d apologies for the delay. I only had a few comments. I'm mostly concerned about not testing the old protocol and compressor for anyone not using proto 5.

File: conn.go (hunk 66 above)
Comment (worryg0d) [reply conn.go:813]: From my point of view, it is not possible.

`bytesToRead` is the amount of bytes left to read from other segments to obtain the completed frame when the segment is not self-contained.  Frame has [length]( https://github.com/apache/cassandra/blob/75ae84534476b7abf1650066898436625bbdcd3a/doc/native_protocol_v5.spec#L224) field which indicates the size of the body.

This part of the code is responsible for reading the whole frame if it is segmented. By segmented, I mean it is being sent in more than one segment.

On line 798 it read and deserialized a frame header from the first segment. The frame header appears **only** in the first segment. After it computed the number of bytes of the frame **body** left to read from other segments. The number is computed by this equation:
```
FrameBodyLength - ReadFrameLength + FrameHeaderLength,
```
where: 
1. FrameBodyLength - length of the frame body
2. ReadFrameLength - length of the frame that was read from the connection
3. FrameHeaderLength - length of the frame header

Following this over-reading looks not possible here.

File: go.mod (hunk 67 above)
Comment (worryg0d) [reply go.mod]: When I was trying to run tests over lz4 pkg with changes I faced compilation errors. It looks like go uses vendored `cassandra-gocql-driver/lz4` instead of local, so I decided to add this. There is PR #1842 that moves `lz4` to `gocql` module. If it is merged first, It will enable me to remove this `replace`.

File: .github/workflows/main.yml (hunk 68 above)
Comment (worryg0d) [reply .github/workflows/main.yml]: I think leaving tests for proto4 is a good idea. I'll try to update this

File: .github/workflows/main.yml (hunk 69 above)
Comment (worryg0d) [reply .github/workflows/main.yml]: Snappy is not supported by proto 5, but it still should be tested for other proto versions.

File: go.mod (hunk 67 above)
Comment (joao-r-reis) [reply go.mod]: Yeah I think we should merge #1842 first, can you take a quick look @jameshartig ? It is very small

**Comment by worryg0d** [comment]
@jameshartig Thanks a lot for the feedback! I'll try to update the CI matrix to run tests on proto 4 + snappy and proto 5 + lz4

**Comment by worryg0d** [comment]
Hello @jameshartig @joao-r-reis. I added to the CI matrix proto version and snappy compressor to run tests over both versions and compressors.

I also squashed all commits and changed a commit message.

One thing I left is replacing in go.mod until #1842 is merged.

Could you please review the CI changes and approve the workflow run? Thanks!

File: cassandra_test.go [hunk 70]
```diff
@@ -3256,6 +3256,10 @@ func TestCreateSession_DontSwallowError(t *testing.T) {
 func TestControl_DiscoverProtocol(t *testing.T) {
 	cluster := createCluster()
 	cluster.ProtoVersion = 0
+	// Forcing to run this test without any compression.
+	// If compressor is presented, then CI will fail when snappy compression is enabled, since
+	// protocol v5 doesn't support it.
+	cluster.Compressor = nil
```
Comment (ribaraka) [inline cassandra_test.go:3262]: You've exluded the snappy from proto v5 in the CI, then everyting should work fine. This block of code is likely unnecessary, isn't it?

File: cassandra_test.go [hunk 71]
```diff
@@ -3362,3 +3366,460 @@ func TestQuery_NamedValues(t *testing.T) {
...
+	//
+	// To trigger C* to return Metadata_changed we should do:
+	// 1. Create a table
+	// 2. Prepare stmt which uses the created table
+	// 3. Change the table schema in order to affect prepared stmt (e.g. add a column)
+	// 4. Execute prepared stmt. As a result C* should return RESULT/ROWS response with
+	//    Metadata_changed flag, new metadata id and updated metadata resultset.
+	//
+	// The driver should handle this by updating its prepared statement inside the cache
+	// when it receives RESULT/ROWS with Metadata_changed flag
```
Comment (ribaraka) [inline cassandra_test.go]: Could you move descriptions above the function declaration?

**Comment by ribaraka** [comment]
The updated CI looks goot to me.

File: cassandra_test.go (hunk 70 above)
Comment (worryg0d) [reply cassandra_test.go:3262]: This test verifies the protocol discovery mechanism by explicitly setting `cluster.ProtoVersion = 0`, so it means that this test doesn't depend on the CI matrix.

The idea behind protocol discovery is to send a query to C* with the newest protocol version that the driver supports, which in this case is proto 5. For instance, the latest proto version supported by Cassandra 3 is proto 4, but the driver supports 5. The driver will send a query with proto 5 version, and C* 3 will return an error with the lowest and greatest proto versions. Then the driver picks the greatest one, which is v4 for C* 3.

The issue comes when CI runs this test with `matrix.proto_version = 4` and `matrix.compressor = snappy`. Proto version is ignored, but not the compressor. So, the driver will send queries with max proto version of 5 and snappy compressor, which causes Cassandra to return an error about unsupported compressor type for protocol v5.

File: cassandra_test.go (hunk 71 above)
Comment (worryg0d) [reply cassandra_test.go]: Done

File: go.mod (hunk 67 above)
Comment (jameshartig) [reply go.mod]: That should be good to merge

**Review by jameshartig — APPROVED** [review]
LGTM and kicked off CI

**Comment by worryg0d** [comment]
Thanks a lot!

I also noticed that [CI](https://github.com/apache/cassandra-gocql-driver/blob/65e2cafa8c46534a1aef83d5483302d23f7cb792/.github/workflows/main.yml#L40) doesn't run tests without any compression. Should I add it to the matrix? With proto v5 it makes sense to add them because we have different segment format for compressed and uncompressed segments

**Comment by worryg0d** [comment]
Fixed conflicts caused by #1842 and deleted `replace` in go.mod

**Comment by joao-r-reis** [comment]
> Thanks a lot!
> 
> I also noticed that [CI](https://github.com/apache/cassandra-gocql-driver/blob/65e2cafa8c46534a1aef83d5483302d23f7cb792/.github/workflows/main.yml#L40) doesn't run tests without any compression. Should I add it to the matrix? With proto v5 it makes sense to add them because we have different segment format for compressed and uncompressed segments

This makes sense, sorry to take a long time to get back to this, do you mind adding this before we merge?

**Comment by worryg0d** [comment]
> sorry to take a long time to get back to this

It's OK! We all have some other work to deal with.

> do you mind adding this before we merge

I think we can handle it in this PR. I pushed the commit which adds `no-compression` compressor to the matrix. I'll squash commits when CI run in my fork will successfully finish

**Comment by worryg0d** [comment]
I ran it [here](https://github.com/worryg0d/gocql/actions/runs/13925892103/job/38970260599?pr=15) and 72 jobs passed successfully. However, running 72 jobs is a bit extreme. 
The CI and tests should probably be optimized in the future. Preparing a bunch of tests for just compressor functionalities sounds good to me. I don't see much gain running all integration tests through different compressors.

**Comment by joao-r-reis** [comment]
> I ran it [here](https://github.com/worryg0d/gocql/actions/runs/13925892103/job/38970260599?pr=15) and 72 jobs passed successfully. However, running 72 jobs is a bit extreme. The CI and tests should probably be optimized in the future. Preparing a bunch of tests for just compressor functionalities sounds good to me. I don't see much gain running all integration tests through different compressors.

I think we can do some optimization on the matrix, maybe making the older go version run a single combination, I don't see much gain in running every combination for both go versions. I'll take care of this after merging this PR

**Comment by worryg0d** [comment]
Thanks a lot for everyone who have been involved in this!

**Comment by joao-r-reis** [comment]
Huge milestone, very good work by everyone involved 👍
