### PR TITLE
CASSGO-6 Accept peers with empty rack

### LINKED ISSUE #1706: Unable to discover cluster nodes with an empty rack name
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.11.8, 4.0.3

### What version of Gocql are you using?
1.5.2

### What version of Go are you using?
1.20.3

We have a client who is using gocql to connect to a Cassandra cluster which has been configured with an empty rack name on all nodes. What we are seeing is that gocql is unable to discover the cluster topology and it only sends requests to the initial contact point(s).
When using the Java driver against this cluster it works just fine and discovers all of the nodes correctly. The difference appears to be that they filter out nodes that have a NULL rack name in system.peers[_v2] and gocql filters out nodes with an empty string in the rack name.

I have been able to reproduce this in a lab environment on Cassandra 3.11 and 4.0 by using GossipingPropertyFileSnitch and setting the rack to an empty string in cassandra-rackdc.properties.

### PR DESCRIPTION
**Pull request by jameshartig**
This fixes #1706.

### CODE REVIEW

File: host_source.go [hunk 1]
```diff
@@ -720,18 +770,25 @@ func (r *ringDescriber) getClusterPeerInfo(localHost *HostInfo) ([]*HostInfo, er
...
 		if err != nil {
-			return nil, err
-		} else if !isValidPeer(host) {
+			// if the error came from the iterator then return it, otherwise ignore
+			// and warn
+			if iterErr := iter.Close(); iterErr != nil {
+				return nil, fmt.Errorf("unable to fetch peer host info: %s", iterErr)
+			}
+			// skip over peers that we couldn't parse
+			r.session.logger.Warning("Failed to parse peer this host will be ignored.", newLogFieldError("err", err))
```
Comment (jameshartig) [inline host_source.go:785]: This technically changes the behavior but this seems reasonable? @joao-r-reis thoughts?

File: control.go [hunk 2]
```diff
@@ -322,7 +322,11 @@ func (c *controlConn) setupConn(conn *Conn, sessionInit bool) error {
 	iter := conn.querySystemLocal(context.TODO())
 	host, err := c.session.hostInfoFromIter(iter, conn.host.connectAddress, conn.r.RemoteAddr().(*net.TCPAddr).Port)
 	if err != nil {
-		return err
+		iter.Close()
```
Comment (joao-r-reis) [inline control.go:326]: Should we handle the error returned by Close()?

File: host_source.go [hunk 3]
```diff
@@ -413,8 +414,9 @@ func (h *HostInfo) update(from *HostInfo) {
 	if h.dataCenter == "" {
 		h.dataCenter = from.dataCenter
 	}
-	if h.rack == "" {
+	if h.missingRack || h.rack == "" {
```
Comment (joao-r-reis) [inline host_source.go]: Maybe we should remove the `h.rack == ""` from here? If now we treat `""` as a valid rack.

File: host_source.go [hunk 4]
```diff
@@ -700,8 +747,12 @@ func (r *ringDescriber) getLocalHostInfo() (*HostInfo, error) {
 
 	host, err := r.session.hostInfoFromIter(iter, nil, r.session.cfg.Port)
 	if err != nil {
+		iter.Close()
```
Comment (joao-r-reis) [inline host_source.go:751]: Same as above, should we handle the error returned by this call?

File: host_source.go (hunk 1 above)
Comment (joao-r-reis) [reply host_source.go:785]: Yeah seems reasonable to me

File: host_source.go [hunk 5]
```diff
@@ -720,18 +770,25 @@ func (r *ringDescriber) getClusterPeerInfo(localHost *HostInfo) ([]*HostInfo, er
...
+			if iterErr := iter.Close(); iterErr != nil {
+				return nil, fmt.Errorf("unable to fetch peer host info: %s", iterErr)
+			}
+			// skip over peers that we couldn't parse
+			r.session.logger.Warning("Failed to parse peer this host will be ignored.", newLogFieldError("err", err))
+			continue
+		}
+		// if nil then none left
+		if host == nil {
+			break
```
Comment (joao-r-reis) [inline host_source.go:790]: Is this ever a scenario? I'm reading the code and it doesn't look like it. It doesn't look like `hostInfoFromMap` can ever return a nil host. It should return either `nil, err` or `host, nil` where host is never nil.

File: host_source.go [hunk 6]
```diff
@@ -700,8 +747,12 @@ func (r *ringDescriber) getLocalHostInfo() (*HostInfo, error) {
 
 	host, err := r.session.hostInfoFromIter(iter, nil, r.session.cfg.Port)
 	if err != nil {
+		iter.Close()
 		return nil, fmt.Errorf("could not retrieve local host info: %w", err)
 	}
+	if host == nil {
+		return nil, errors.New("could not retrieve local host info: query returned 0 rows")
+	}
```
Comment (joao-r-reis) [inline host_source.go:756]: Same as my other comment, doesn't look like `host` can ever be `nil`

**Review by joao-r-reis — COMMENTED** [review]
Looks good, left a few comments

File: control.go (hunk 2 above)
Comment (jameshartig) [reply control.go:326]: This was mostly to just cleanup the iterator. We should probably return the error from `hostInfoFromIter`.

File: host_source.go (hunk 3 above)
Comment (jameshartig) [reply host_source.go]: Yeah, I could see that, I was trying to handle filling in the rack if it was empty but since "" is valid I should remove it.

File: host_source.go (hunk 4 above)
Comment (jameshartig) [reply host_source.go:751]: This was just to cleanup the iterator.

File: host_source.go (hunk 5 above)
Comment (jameshartig) [reply host_source.go:790]: It can now return `nil, nil`. I documented that:
> // this will return nil, nil if there were no rows left in the Iter

**Review by joao-r-reis — APPROVED** [review]

**Comment by joao-r-reis** [comment]
Looks good, don't forget to update commit message before merging
