### PR TITLE
Mark node as down if pool filling failed and pool is empty

### LINKED ISSUE #1614: Failed host is never reconnected if NumConns > 1
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
Yugabyte 2.8

### What version of Gocql are you using?
v1.0.0

### What version of Go are you using?
go 1.17

### What did you do?
`cluster.NumConns = 2`

Node was terminated and both connections closed which called `closeWithError` which ended up calling `hostConnPool.HandleError` and `hostConnPool.fill`. Unfortunately `hostConnPool.fill` was called twice and the first time failed to connect but since `startCount` was still `1` (since the other connection is blocked on `pool.mu`). The second time didn't do anything in `fill` because `filling = true` since the first goroutine is stuck in `fillingStopped`.

### What did you expect to see?
I expected to see the node eventually reconnect.

### What did you see instead?
The host is in a stuck state where the pool is empty and set the ring status is `Up`. This means it will never reconnect.

Unfortunately, I didn't have a chance to look at the `system.peers` table while it was down but I assume that the node was still present otherwise it would've removed from the ring when it was refreshed.
---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

### PR DESCRIPTION
**Pull request by jameshartig**
Previously if the `NumConns > 1` there was a race to fill the pool and we only ever marked the host as down if the `startCount == 0` but if 2 connections failed simultaneously there would be a race and not always would the startCount be 0. Therefore we now check whenever filling stops to see if the pool is empty and if so, mark as down.

Fixes #1614

### CODE REVIEW

File: connectionpool.go [hunk 1]
```diff
@@ -486,7 +483,21 @@ func (pool *hostConnPool) fillingStopped(hadError bool) {
...
 	pool.mu.Unlock()
+
+	// if we errored and the size is now zero, make sure the host is marked as down
+	// see https://github.com/gocql/gocql/issues/1614
+	if gocqlDebug {
+		pool.logger.Printf("gocql: conns of pool after stopped %q: %v\n", host.ConnectAddress(), count)
+	}
+	if err != nil && count == 0 {
+		if pool.session.cfg.ConvictionPolicy.AddFailure(err, host) {
+			pool.session.handleNodeDown(host.ConnectAddress(), port)
```
Comment (martin-sucha) [inline connectionpool.go:498]: Previously, `handleNodeDown` was called in a new goroutine. Is it safe to call it directly?

Comment (jameshartig) [reply connectionpool.go:498]: Yeah, there was a comment about that. Previously it was called in a goroutine to avoid a deadlock but now it's called within `fillingStopped` which is called within an anonymous goroutine at the end of `fill`. So it's still in a goroutine w/r/t `fill`.

**Comment by martin-sucha** [comment]
Merged. Thanks for the contribution!
